#+TITLE: Data Plane - Arquitectura de routers, IP y framentacion

the network layer can be decomposed into two interacting parts, the =data plane=
and the =control plane=.

the data plane functions of the network layer—the per-router functions in the
network layer that determine how a datagram (that is, a network-layer packet)
arriving on one of a router’s input links is forwarded to one of that router’s
output links.

the control plane functions of the network layer—the network-wide logic that
controls how a datagram is routed among routers along an end-to-end path from
the source host to the destination host.

Traditionally, these control-plane routing protocols and data-plane forwarding
functions have been implemented together, monolithically, within a router.

Software-defined networking (SDN) explicitly separates the data plane and
control plane by implementing these control plane functions as a separate
service, typically in a remote “controller.”

This distinction between data-plane and control-plane functions in the network
layer is an important concept to keep in mind as you learn about the network
layer —it will help structure your thinking about the network layer and reflects
a modern view of the network layer’s role in computer networking.

* Overview of the Network Layer
