#+title: Introducción a la Simulación numérica
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://thomasf.github.io/solarized-css/solarized-dark.min.css"/>

* Introducción a la Simulación

** Qué es la simulación numérica?
   Desarrollo de la ciencia y la tecnología a través de la observación y derivación
   de teorías que explican satisfactoriamente las observaciones.

   Con la introducción de las computadores fue posible reproducir observaciones
   aplicando expresiones matemáticas = SIMULACIÓN

   Modelo matemático + Computadora = Simulación

** Por qué necesitamos simular numéricamente?
   No existe una solución analítica

   Sistemas complejos con muchas variables, parámetros y ecuaciones.

   La simulación es una actividad multidisciplinaria que involucra investigadores,
   ingenieros y desarrolladores

   Matemáticos Físicos Químicos
   Ingenieros Programadores Desarrolladores

*** Aplicaciones de la simulación numérica:
    En Investigación Científica

    En diseños de Ingeniería

    - Industria automotriz
    - Neurociencias
    - Energía
    - Astronomía


** Un poco de historia


   1945: Primer computadora electrónica ENIAC (Simulación de trayectorias
   balísticas, primer modelo meteorológico de John Von Neumann) - 400 FLOPS

   Documental en Youtube “Top Secret Rosies The Female Computers of WWII
   Documentary”

   1959: IBM 704: Ed Lorentz descubre el comportamiento caótico del proceso
   meteorológico - 12 KFLOPS

   Atractor de Lorentz (sistema caótico)

** Top List de Supercomputadoras (Nov. 2017)

* El proceso de modelado y Tipos de sistemas

** El proceso de modelado
   Ejemplo: Supongamos que queremos modelar y simular el recorrido de un vehículo
   a lo largo de una determinada ruta.

   Para qué?
   (Fijar objetivos)

   - Planeamiento urbano: Diseñar rutas y/o control de tránsito (semáforos, ancho
     de calles, velocidades máximas) para minimizar la congestión de la red.

   - Diseño automotores: minimizar uso de combustible o minimizar el tiempo del
     recorrido.

** Paso 1: determinar variables

*** Ejemplo planeamiento urbano

    Variables que podemos controlar:
    - Ancho de calles y avenidas
    - Ubicación de semáforos
    - Coordinación y tiempo de luces de semáforos
    - Velocidades máximas

    Variables de entorno (no controlamos)
    - Número de automóviles por hora

*** Ejemplo diseño automóvil

    Variables que podemos controlar:
    - Tipo de motor (cilindrada, respuesta a la aceleración, etc)
    - Aerodinámica
    - Sistema de tracción (rodado)
    - Sistema de velocidades (automático, manual)

    Variables de entorno (no controlamos)
    - Número de automóviles
    - Ancho de calles y avenidas
    - Ubicación de semáforos
    - Coordinación y tiempo de luces de semáforos
    - Velocidades máximas


** Paso 2: Entender como afectan cada una de las variables al objetivo de la simulación

*** Ejemplo planeamiento urbano

    Ancho de calles y avenidas            -> Congestión de la red
    Ubicación y coordinación de semáforos -> Congestión de la red
    Número de automóviles -> Velocidad    -> Congestión de la red


*** Ejemplo diseño automóvil
    Cilindrada -> Consumo de combustible
    Aerodinámica -> Consumo de combustible
    Utilización de velocidades  -> Consumo de combustible
    (aceleración/frenado)

** Paso 3: Determinar leyes físicas o matemáticas que relacionan las variables del sistema

   Determinísticos

   Estocásticos o Probabilísticos

** Tipos de sistemas

   F(t)

   <latexit sha1_base64="QGNrLFkh6T+/CsW7jcCiXtfjucM=">AAACAXicbZDLSgMxFIYz9VbrrepGcBMsgiCWGRF0IxR14bKCvUA7lEx62oZmMkNyRihD3fgqblwo4ta3cOfbmF4W2nog8PH/53By/iCWwqDrfjuZhcWl5ZXsam5tfWNzK7+9UzVRojlUeCQjXQ+YASkUVFCghHqsgYWBhFrQvx75tQfQRkTqHgcx+CHrKtERnKGVWvm95g1IZC2klxRbqTr2hvTEkrUKbtEdF50HbwoFMq1yK//VbEc8CUEhl8yYhufG6KdMo+AShrlmYiBmvM+60LCoWAjGT8cXDOmhVdq0E2n7FNKx+nsiZaExgzCwnSHDnpn1RuJ/XiPBzoWfChUnCIpPFnUSSTGiozhoW2jgKAcWGNfC/pXyHtOMow0tZ0PwZk+eh+pp0XOL3t1ZoXQ1jSNL9skBOSIeOSclckvKpEI4eSTP5JW8OU/Oi/PufExaM850Zpf8KefzBz7glXQ=</latexit>

   r(t)

   tn
   <latexit sha1_base64="O+Ovq9mo4N256ewbGHtYUC+Z34E=">AAAB6nicbVBNS8NAEJ3Ur1q/oh69LBbBU0lE0GPRi8eK9gPaUDbbTbt0swm7E6GE/gQvHhTx6i/y5r9x2+agrQ8GHu/NMDMvTKUw6HnfTmltfWNzq7xd2dnd2z9wD49aJsk0402WyER3Qmq4FIo3UaDknVRzGoeSt8Px7cxvP3FtRKIecZLyIKZDJSLBKFrpAfuq71a9mjcHWSV+QapQoNF3v3qDhGUxV8gkNabreykGOdUomOTTSi8zPKVsTIe8a6miMTdBPj91Ss6sMiBRom0pJHP190ROY2MmcWg7Y4ojs+zNxP+8bobRdZALlWbIFVssijJJMCGzv8lAaM5QTiyhTAt7K2EjqilDm07FhuAvv7xKWhc136v595fV+k0RRxlO4BTOwYcrqMMdNKAJDIbwDK/w5kjnxXl3PhatJaeYOYY/cD5/AGIMjdk=</latexit>

   t

   = tn+1

   tn+1

   tn

   t

   <latexit sha1_base64="1EHoum5LHGr5Uk3Bd1HuUPLTJn0=">AAAB7nicbVBNS8NAEJ3Ur1q/qh69LBZBEEoigh6LXjxWsB/QhrLZbtqlm03YnQgl9Ed48aCIV3+PN/+NmzYHbX0w8Hhvhpl5QSKFQdf9dkpr6xubW+Xtys7u3v5B9fCobeJUM95isYx1N6CGS6F4CwVK3k00p1EgeSeY3OV+54lrI2L1iNOE+xEdKREKRtFKHRxk6sKbDao1t+7OQVaJV5AaFGgOql/9YczSiCtkkhrT89wE/YxqFEzyWaWfGp5QNqEj3rNU0YgbP5ufOyNnVhmSMNa2FJK5+nsio5Ex0yiwnRHFsVn2cvE/r5dieONnQiUpcsUWi8JUEoxJ/jsZCs0ZyqkllGlhbyVsTDVlaBOq2BC85ZdXSfuy7rl17+Gq1rgt4ijDCZzCOXhwDQ24hya0gMEEnuEV3pzEeXHenY9Fa8kpZo7hD5zPHwA+j1U=</latexit>

   En el modelo matemático la variable tiempo puede ser:


   | Continua                                   | Discreta                                           |
   | Posición: $r(t)$                           | $r(t_{n+1} ) = r(t_{n} ) + v(t_{n} ) * \Delta_{t}$ |
   | Velocidad: $v(t) = $r^{'}(t)$              | $v(t_{n+1}) = v(t_{n}) + a(t_{n}) * \Delta_{t}$    |
   | Aceleración: $a(t) = v^{'}(t) = r^{''}(t)$ |                                                    |

   Nota: La implementación de un modelo continuo en la computadora generalmente
   se hace mediante una discretización

   Dependiendo de cómo se realiza la actualización de variables, un modelo puede
   resolverse:

   | Analíticamente                             | Numéricamente   (discretizando)                    |
   | Posición: $r(t)$                           | $r(t_{n+1} ) = r(t_{n} ) + v(t_{n} ) * \Delta_{t}$ |
   | Velocidad: $v(t) = $r^{'}(t)$              | $v(t_{n+1}) = v(t_{n}) + a(t_{n}) * \Delta_{t}$    |
   | Aceleración: $a(t) = v^{'}(t) = r^{''}(t)$ |                                                    |

   Solución (si *F* es cte):

   $r(t) = r(t_0 ) + r^{'}(t_0 )t + \frac{\textbf{F}t^2}{m}$

   Nota: En la práctica, rara vez los modelos pueden resolverse analíticamente
   por lo que debemos utilizar métodos numéricos.

   En un sistema dinámico las variables se relacionan
   a través de un sistema de ecuaciones diferenciales

   $\frac{d\textbf{x}}{dt}=F(\textbf{x},t)$

   Ejemplos: Péndulo (física), Leyes de movimiento de planetas (Astronomía),
   Interacción de especies (Biología), contagio de enfermedades (Epidemiología),
   etc.

   Definiciones:
   - Espacio de fases: Espacio de donde viven las variables $x_1, x_2, \dots,$ etc.
   - Punto fijo: Punto del espacio de fases donde se cumple que $\frac{d\textbf{x}}{dt}=\textbf{0}$

   | Caso Lineal                                     | Caso Nolineal                                                     |
   | $\frac{d\textbf{x}}{dt}=\textbf{Ax}$            | $\frac{d\textbf{x}}{dt}=F(\textbf{x},t)$                          |
   | Se pueden resolver analíticamente.              | Se resuelven numéricamente                                        |
   | Existe un solo punto fijo                       | Puede existir más de un punto fijo                                |
   | La dinamica es simple (estables o   inestables) | La dinámica es compleja. Puede observarse comportamiento caótico. |

* Ejemplos (papers)

** Ejemplo1: Emergencias aéreas

   Aplicando las leyes de dinámica de fluidos y técnicas computacionales se
   simula el impacto en aeronaves al contacto con el agua.

   “Malaysia Airlines Flight MH370: Water Entry
   of an Airliner”, G. Chen, C. Gu, P. J. Morris, E.
   G. Paterson, A. Sergeev, Notices of the AMS,
   64 (4), 2015.

   The water entry problem
   Added mass model
   (Karman [1881 - 1963] )

   M: Masa avión
   m: added mass
   FB, FC, FD: fuerzas

*** Amerizaje de emergencia
    Caso I: ángulo = 8 grados

    Caso II: ángulo = -3 grados

*** Caída no controlada
    Caso I: ángulo = -30 grados

    Caso II: ángulo = -90 grados

    Conclusión: una caída en 90 grados del avión MH370
    (Malaysia Airlines) explicaría la ausencia de restos del avión

** Ejemplo 2: Evacuación de personas en situación de emergencia

   Comportamiento de muchedumbres (gran cantidad de personas en un espacio
   reducido).

   Modelo matemático basado en Sistemas Multiagentes: a partir de reglas de
   comportamiento individual, emergen comportamientos globales.

   -

   Modelos similares: comportamiento de bandadas de pájaros (boids) [Reynolds,
   1987]. Tres reglas locales:

   1) Separación (evitar colisiones)
   2) Alineamiento (misma dirección que vecinos)
   3) Cohesión (centro de “masa”)

   Separación
   Alineamiento
   Cohesión

   Paper: “Aggregate Dynamics for Dense Crowd Simulation”. R.  Narain, A. Golas,
   S. Curtis and M. C. Lin, 2009.  In ACM Transactions on Graphics (Proceedings
   of SIGGRAPH Asia), vol.  28, no. 5, pp. 122:1–122:8.

   Dense Crows Simulation:
   - Modelo de tipo Reynolds
   - 100,000 agentes simulados con una PC de escritorio en tiempo real (24 fps)

* Material de Lectura
  - Sobre la clase de hoy:
    - Libros (mínimo):
      - [1] Introduction to Modeling and Simulation with Matlab and Python -
        Gordon and Guilfoos, Cap. 1, pags. 1 - 18.
      - [2] Introduction to the Modeling and Analysis of Complex Systems -
        Sayama, Cap 2, pags. 11 - 25.
      - [5] Intuitive Probability and Random Processes Using MatLab - Steven
        M. Kay, Cap 2, pags. 13 - 30.
    - Papers (opcional):
      - G. Chen, C. Gu, P. J. Morris, E. G. Paterson, A. Sergeev, Y.-C. Wang, and
        T. Wierzbicki. “Malaysia airlines flight MH370: water entry of an
        airliner”. In: Notices of the AMS 62.4 (2015), pp. 330–344.
      - Rahul Narain, Abhinav Golas, Sean Curtis, and Ming
        C. Lin, 2009. Aggregate Dynamics for Dense Crowd Simulation. In ACM
        Transactions on Graphics (Proceedings of SIGGRAPH Asia), vol. 28, no. 5,
        pp. 122:1–122:8.
 
 
 
 
 

