#+title: Procesos Estocásticos

* Introducción

** Qué es un proceso estocástico o aleatorio?
Cuando una magnitud de interés S(t) depende del tiempo t y, a su vez, es de
naturaleza aleatoria, tenemos un proceso estocástico o aleatorio unidimensional
(temporal).

S(t)

t
Tiempo continuo

S(tn)

t
Tiempo discreto
t0 t1 t2 t3

tn

La variable aleatorio S(t) o S(tn) puede ser a su vez continua o discreta.

Ejemplos de procesos 1D:
- Ej. 1: Tirar una moneda 1 vez por segundo y anotar el resultado.
- Ej. 2: Número de vehículos en un estacionamiento en función del tiempo.
- Ej. 3: Temperatura de un sensor en función del tiempo.
- Ej. 4: Número de disparos (spikes) de una neurona en un intervalo de tiempo
- Ej. 5: Número de clientes en una cola de un banco en función del tiempo.

Formalmente: un proceso estocástico es una familia de variables aleatorias
indexadas por el tiempo, espacio u otra variable.




Procesos estocásticos

Cada repetición del experimento aleatorio da como resultado una realización
del proceso estocástico.





Procesos estocásticos multidimensionales:
Campos aleatorios


6

Ejemplo: Procesamiento de Imágenes 2D

Xi,j


Xi

1

Xi,j Xi+1,j

1,j

Xi,j+1

2D random field:

{Xi,j }

8i = 1, 2, . . . , I
8j = 1, 2, . . . , J


Applicación de campos aleatorios para el “denoising” de
imágenes astronómicas



Cosmic Microwave
Background (CMB) - Satellite Planck

Resultado de “denoising” usando un modelo de campo aleatorio
Gaussiano con correlaciones de largo alcance para el CMB y ruido
Gaussiona nocorrelacionado para el ruido

“Long Correlation Gaussian Random Fields: Parameter Estimation and Noise Reduction”, C. F. Caiafa,
A. N. Proto, E. E. Kuruoglu, Digital Signal Processing, Volume 17, pp. 819-835, 2007 (Elsevier)




Modelos probabilísticos para procesos Estocásticos



La descripción completa de un proceso estocástico X(tn) está dada por la
distribución conjunta de todas las variables aleatorias que lo conforman, es
decir:

Para hacer manejable la matemática es necesario simplificar las
probabilidades conjuntas a casos más sencillos.
Por ejemplo: Asumir variables aleatorias i.i.d. (independent and identically
distributed)


Casos particulares con variables i.i.d


Caracterización de procesos a través de momentos


Describir a los procesos a través de momentos en lugar de sus distribuciones
conjuntas
Media
Varianza
Autocorrelación

Ejercicio: demostrar que

V AR[Xn ] =

2

for all n


RX (n1 , n2 ) =

2

{ m0

2


+ m2

si n1 = n2
6 n2
si n1 =


Procesos estocásticos estacionarios

11

Un proceso es estacionario si la distribución conjunta de cualquier conjunto
de variables no depende de un desplazamiento en el tiempo.

Ejercicio: demostrar que si un proceso es estacionario, entonces se cumple:

Wide-sense stationary (WSS)

Nota importante:
proceso estacionario
Wide-sense stationary (WSS)


Wide-sense stationary (WSS)
proceso estacionario


Procesos de Poisson

Procesos de Poisson

13

Un proceso de Poisson surge al considerar número de eventos que ocurren a
lo largo del tiempo.
Ejemplos:
- Número de clientes que llegan a un banco.
- Número de disparos en una neurona.
- Número de llamadas telefónicas recibidas en una central.

N(t): Número de eventos
x: Eventos
Tiempo continuo
Valores discretos





Derivación de un proceso de Poisson
como el límite de una binomial

14

M: Número de celdas
t : Ancho de celdas
p: Probabilidad éxito

Discretizamos el eje de tiempos y
consideramos la variable de Bernoulli
U(n) = 1 si hay un evento en la celda n
o U(n) = 0 si no lo hay, con una
probabilidad de éxito igual a p.


Binomial:
Consideremos: M ! 1 , p ! 0 ,

P [N (t) = k] ⇡ lim

M (M



t!0 y

1)(M

M !1

k

M + O(M
= lim
M !1
k!

k 1

k

) ( t)
Mk


✓

1

t
M

◆M

p
=
constante
t

2) · · · (M
k!
k

k + 1)

( t)
= lim
M !1 k!

t
Finalmente: P [N (t) = k] = e
k!

t

k

✓

✓

1

t
M

◆k ✓

t
M

t
M

1

◆M

◆M

k

k

M !1

e

t



Proceso de Poisson



Proceso de Poisson: propiedades (I)

15

: Tasa de arribos o frecuencia de eventos por unidad de tiempo

Media y varianza
Incrementos independientes

N (t)

A
(k1 )


B
(k2 )



x

t1

P [N (t2 )



t2

x x


t3

N (t1 ) = k1 , N (t4 )



xx x



P [A, B] = P [A]P [B]

x

x

x

x

t4

N (t3 ) = k2 ] = P [N (t2 )

t


N (t1 ) = k1 ]P [N (t4 )

N (t3 ) = k2 ]

Incrementos estacionarios

N (t)

A
(k)

B
(k)



x

x


t1

x


x

x xx


t1 + ⌧

P [N (t1 + ⌧ )


P [A] = P [B]


t2

x

x

x

x

t2 + ⌧

N (t1 ) = k] = P [N (t2 + ⌧ )



t

N (t2 ) = k] = P [N (⌧ ) = k]


Proceso de Poisson: propiedades (I)

16

Variable aleatoria Zn: tiempos entre eventos

Memoryless property:





Proceso de Poisson: Ejemplos



17



Proceso de Poisson: Ejemplos



18



Simulación de un proceso de Poisson

19

Método para generar eventos de Poisson
1- Generar muestras de una distribución exponencial Z
con parámetro :


z1, z2, …, zN.
2- Definir tiempos de eventos conteo de Poisson
t0=0, t1=t0+z1, t2=t1+z2, t3=t2+z3, …
N(t0)=0, N(t1)=N(t0)+1 , N(t2)=N(t1)+1, …





* Material de Lectura
- Sobre la clase de hoy:
  - Libros (Mínimo):
    - [15] Probability, Statistics, and Random Processes for Eletrical
      Engineerging, 3rd_Ed. - Leon-Garcia., Cap 9.1-4.
    - [5] Intuitive Probability and Random Processes Using MatLab - Steven M.
      Kay, Cap 21.

  - Libros (opcional):
    - [16] Performance Modeling and Design of Computer Systems: Queueing Theory
      in Action, Mor Harchol-Balter, 2013, Cap 11
    - [19] Introduction to probability models, Ross Sheldon, 2007, Cap 5.

- Leer para la próxima clase:
  - Libros (Mínimo):
    - [15] Probability, Statistics, and Random Processes for Eletrical Engineerging, 3rd_Ed. - Leon-Garcia., Cap 11.
    - [5] Intuitive Probability and Random Processes Using MatLab - Steven M. Kay, Cap 22.

  - Libros (opcional):
    - [16] Performance Modeling and Design of Computer Systems: Queueing Theory
      in Action, Mor Harchol-Balter, 2013, Cap 8-10
    - [19] Introduction to probability models, Ross Sheldon, 2007, Cap 4.

               