#+title:Sistemas complejos

* Sistemas complejos

** Qué es un sistema complejo?

   Los sistemas complejos son redes formadas a partir de un numero de
   componentes que interactuan entre si, tipicamente de una forma no lineal. Los
   sistemas complejos pueden surgir y evolucionar mediante la
   *self-organization*, de forma tal que no son completamente regulares ni
   completamente aleatorios, permitiendo el desarrollo de comportamiento
   emergente en una escala macroscopica

   Por ejemplo:
   - Sistema climático
   - Internet
   - Sistemas económicos
   - Redes sociales
   - Ecosistemas biológicos
   - Poblaciones y enfermedades

   - Sistemas NO-COMPLEJOS
     - Conjunto de componentes independientes (por ej. Gas ideal)
       - Modelos estadísticos
     - Conjunto de componentes fuertemente acoplados (por ej. Cuerpo rígido)
       - Modelos determinísticos

* Sistemas dinámicos

** Qué es un sistema dinámico?

   Un sistema dinamico es un sistema cuyo estado es especificado unicamente por un
   conjunto de variables y cuyo comportamiento es descrito por reglas predefinidas

   Por ejemplo:
   - Crecimiento de población
   - Péndulo
   - Movimiento de planetas
   - Sistema financiero

   Sistema dinamico de tiempos discretos $x_t = F(x_{t-1},t)$ Este tipo de modelo
   lo llama ecuacion de diferencia, ecuacion de recurrencia o un mapa iterativo (si
   no existe $t$ del lado derecho de la ecuacion).

   Sistema dinamico de tiempos continuos $\frac{dx}{dt} = F(x,t)$
   Este tipo de modelo se lo llama ecuacion diferencial.

   Nota 1: $x$ es un vector de *variables de estado* del sistema

   Nota 2: Estas ecuaciones son de *primer orden* pero son suficientes para
   describir un sistema dinámico de cualquier orden.

** Espacio de Fases

   El *espacio de fases* es donde viven las *variables de estado* del sistema.
   Cualquier estado del sistema se representa unívocamente por un punto en el
   espacio de fases.

   Un sistema dinámico evoluciona en el tiempo como una *trayectoria* en el espacio
   de fases.


   diag


** Espacio de Fases
   ejercicio
   diag

** Propiedades del espacio de Fases

   En un *sistema deterministico*, las *trayectorias nunca se bifurcan* ya que
   no pueden existir múltiples estados futuros a partir de una única condición
   inicial.

   Comportamiento de trayectorias:
   - Diverger a infinito
   - Converger a un punto fijo estable (Atractor)
   - Oscilar alrededor de un punto (ciclo límite) (Atractor)

   Cuenca de un atractor: conjunto de puntos en el espacio de fases que llevan a
   un atractor

** Atractores, cuencas, puntos fijos inestables y ciclos límite

   diag

   Atractor (punto fijo estable)
   Cuenca de atractor
   Punto fijo inestable
   Ciclo límite (atractor)

** Ecuaciones de diferencia (tiempo discreto)

   Los sistemas dinámicos en tiempo discreto son fáciles de entender y simular.

   Ecuación de diferencia
   $$ x_{t+1} = F(x_t,t)$$


   Serie temporal
   $$\{x_0,x_1,x_2,x_3,\dots\} $$

   - Sistema lineal :: una ecuacion dinamica cuyas reglas involucran solamente una
                       combinacion lineal de variables de estado (una constante por
                       una variable, una constante, o su suma).
   - Sistema no lineal :: Cualquier otra cosa (ecuacion que involucra cuadrados,
        cubos, radicales, funciones trigonometricas, etc, de variables de estado).

   - Sistema autonomo :: una ecuacion dinamica cuyas reglas no incluyen el tiempo
        $t$ o ningun otra variable externa de forma explicita.
   - Sistemas no autonomos :: una ecuacion dinamica cuyas reglas si incluyen el
        tiempo $t$ u otra variable externa de forma explicita.

   - Sistema de primer orden :: una ecuacion de diferencia cuyas reglas involucran
        variables de estado del pasado inmediato solamente (en el tiempo $t-1$).
   - Sistemas de mayor orden :: cualquier otra cosa.

** Ejemplos (1 dimensión)

   | $x_t = ax_{t-1}+b$                      | Lineal    | Autónomo    | 1er Orden |
   | $x_t = ax_{t-1}+bx_{t-2}+cx_{t-3}$      | Lineal    | Autónomo    | 3er Orden |
   | $x_t = ax_{t-1}(1-x_{t-1})$             | NO-Lineal | Autónomo    | 1er Orden |
   | $x_t = ax_{t-1}x_{t-2}+bx_{t-3}+\sin t$ | NO-Lineal | NO-Autónomo | 3er Orden |

** Reducción a sistemas autónomos de 1er orden

   Cualquier sistema dinámico puede escribirse como un *sistema autónomo de
   primer orden* definiendo nuevas variables de estado (aumentando la
   dimensión).

   Ejemplo 1: sistema orden 2

   $x_t = x_{t-1} + x_{t-2}$ Serie de Fibonacci

   Nueva variable de estado $y_t = x_{t-1}
   \longrightarrow \begin{matrix}x_t=x_{t-1} + y_{t-1}
   \\ y_t=x_{t-1}\end{matrix}$ sistema con dos dimensiones


   Ejemplo 2: sistema NO-autónomo

   $x_t = x_{t-1} + t$

   Nueva variable de estado (clock) $z_t = z_{t-1}+1, z_0 = 1
   \longrightarrow \begin{matrix}x_t=x_{t-1} + z_{t-1}
   \\ z_t=z_{t-1}+1\end{matrix}$ Sistema con 2 dimensiones

* Sistemas dinámicos Lineales

** Comportamiento de sistemas lineales (1)

   Las ecuaciones lineales siempre se pueden resolver de forma analitica, en cambio
   las ecuaciones no lineales no tienen soluciones analiticas en general

   $$\mathbf{x}_t = \mathbf{A} \mathbf{x}_{t-1} +\mathbf{b} \quad
   \mathbf{x}_t,\mathbf{x}_{t-1},\mathbf{b} \in \Re^N \quad \mathbf{A} \in
   \Re^{NxN}$$

   Punto Fijo $x^*$: Todo punto del espacio de fases en donde el sistema permanece
   por siempre, es decir: $\mathbf{x}_t = \mathbf{x}_{t-1}$

   Primer resultado: Existe un único punto fijo en los sistemas lineales y es el
   siguiente: $\mathbf{x}^{*} = -(\mathbf{A} - \mathbf{I})^{-1} \mathbf{b}$,
   siempre y cuando exista la inversa de $(\mathbf{A}- \mathbf{I})$.

   Analizamos el comportamiento en torno al punto fijo $x^*$.

   Definimos $\mathbf{y}_t = \mathbf{x}_t - \mathbf{x}^*$ , entonces
   $\mathbf{y}_t = \mathbf{A}\mathbf{y}_{t-1}

   El estado del sistema luego de $t$ iteraciones será: $\mathbf{y}_t =
   \mathbf{A}^t \mathbf{y}_0$

   Usando la descomposición en autovalores y autovectores: $\mathbf{A} =
   \mathbf{U \Lambda U^T}$

   $$\mathbf{y}_t = \mathbf{U \Lambda^t U^T y}_0$$

   Definimos $\mathbf{u}_t = \mathbf{U}^T \mathbf{y}^t$, entonces finalmente
   $\mathbf{u}_t = \mathbf{\Lambda}^t \mathbf{u}_0$

** Comportamiento de sistemas lineales (2)

   Resumiendo, tenemos un sistema lineal desacoplado: $\mathbf{u}_t = \mathbf{\Lambda}^t\mathbf{u}_0$

   con $\mathbf{u}_t = \mathbf{U}^T (\mathbf{x}_t -\mathbf{x}^*)$

   diag

   $u_{nt} = \lambda_n^t u_{n0}$

   - Autovalores reales o complejos $|\lambda_1|,|\lambda_2|<1$ ATRACTOR (punto
     fijo estable)
   - Autovalores reales o complejos $|\lambda_1|,|\lambda_2|<1$ REPULSOR (punto
     fijo inestable)
   - Autovalores complejos $|\lambda_1| = |\lambda_2| = 1$ CICLO LIMITE
   - Autovalores reales $|\lambda_1|<1,|\lambda_2|>1$ SADDLE POINT

** Ejercicio: sistema lineal

   $$x_t = 0.5x_{t-1}+y_{t-1}+0.25$$
   $$y_t = -0.5x_{t-1}+y_{t-1}+0.75$$

   1. Determine si existe punto fijo y si es único
   2. Determine el tipo de punto fijo
   3. Simule el sistema partiendo de distintas condiciones iniciales y grafique
      las trayectorias en el espacio de fases.





* Ejemplos Sistemas Lineales y NO-Lineales

** Modelos de crecimiento poblacional

   Crecimiento exponencial: $x_t = ax_{t-1}$

   $x_t$ : tamaño de población
   $a$ : tasa de crecimiento

   Ejercicio:
   1. Qué tipo de sistema es?
   2. Encuentre el o los puntos fijos
   3. Clasifique el o los puntos fijos en estables o inestables?
   4. Simule el sistema.

   Crecimiento logístico (Convergencia a población límite)
   $$x_t = f(x_{t-1})x_{t-1} \text{ con } f(x) = - \frac{a-1}{K}x+a$$

   Ejercicio:
   1. Qué tipo de sistema es?
   2. Encuentre el o los puntos fijos
   3. Clasifique el o los puntos fijos en estables o inestables?
   4. Simule el sistema.

** Modelo predador-presa

   diag

   $$x_t = x_{t-1}+tx_{t-1}(1-\frac{x_{t-1}}{K})-d_x(y_{t-1})x_{t-1}$$
   $$y_t = y_{t-1}-dy_{t-1}+r_y(x_{t-1})y_{t-1}$$

   $r$: tasa de crecimiento de presas
   $d_x(y)$: Influencia negativa en presas
   $d$ : tasa de mortalidad de predadores
   $r_y(x)$ : Influencia positiva en predadores

** Modelo predador-presa: simulación
   Influencia negativa en presas
   $d_x(y) = 1-\frac{1}{by+1}

   Influencia positiva en predadores
   $r_y(x) = cx$

   SIMULACION:
   diagrama

* Material de Lectura

  - Libros (Mínimo):
    - [2] Introduction to the Modeling and Analysis of Complex Systems -
      Sayama, Cap 1, 3, 4 y 5.

  - Libros (opcional):
    - [1] Introduction to Modeling and Simulation with Matlab and Python -
      Gordon and Guilfoos, Cap. 9
 
