#+title:Sistemas dinámicos en tiempo continuo

* Sistemas dinámicos en tiempo discreto

** Propiedades sistemas tiempo discreto (1)

   Cualquier sistema dinámico puede escribirse como un sistema autónomo de primer
   orden definiendo nuevas variables de estado (aumentando la dimensión).

   Modelo $$x_t = F(x_{t-1})$$

   Condición Punto Fijo $x^*$: $$x^* = F(x^*)$$

   Tipos de Puntos Fijos:
   - Estable (atractor)
   - Inestable (repulsor)
   - Ciclo límite (atractor)

   diag

** Propiedades sistemas tiempo discreto (2)

   5

   Los sistemas dinámicos lineales tiene un único punto fijo
   El comportamiento está determinado por los autovalores y autovectores de la
   matriz del sistema.
   x1

   u2
   u1

   unt =

   x*



   t
   n un0

   x1

   - Autovalores reales o complejos

   |

   1 |, | 2 |

   <1

   |

   1 |, | 2 |

   >1



   - Autovalores reales o complejos



   |

   - Autovalores complejos



   - Autovalores reales

   |


   1|
   1|

   =|

   < 1, |



   2|

   =1

   2|

   ATRACTOR
   (punto fijo estable)
   REPULSOR
   (punto fijo inestable)
   CICLO LIMITE

   >1

   SADDLE POINT



   Cambio de variables

   6

   A veces es conveniente definir un cambio en la variables de estado para
   simplificar las ecuaciones del sistema.
   Ejemplo: ecuación logística para crecimiento poblacional

   Logistic Map




   Comportamiento asintótico sistemas no-lineales

   7

   Sistemas Lineales: ya lo vimos (un único punto fijo)
   El análisis de la dinamica de sistemas no-lineales es complicado pero lo que
   podemos hacer es analizar el comportamiento en un entorno reducido de los
   puntos fijos.





   Comportamiento asintótico sistemas no-lineales

   8

   En un entorno reducido, el sistema se comporta como un sistema lineal con
   una matriz determinada por el Jacobiano de la función no lineal evaluada en el
   punto fijo

   Sistema Lineal !!!





   Comportamiento asintótico sistemas no-lineales



   9



   Sistemas dinámicos
   en tiempo continuo

   Sistemas dinámicos en tiempo continuo



   11



   Sistemas dinámicos en tiempo continuo

   Ejemplo: Segundo orden

   Introducimos variable “clock”



   12

   Primer orden no-autónomo
   (dos dimensiones)

   Primer orden autónomo
   (3 dimensiones)



   Sistemas dinámicos lineales en tiempo continuo



   13



   Simulación de sistemas no-lineales autónomos
   en tiempo continuo (discretización)

   14

   Método de Euler (MALO!!)

   Método más preciso: Algoritmo de Runge-Kutta orden 4:

   Método más eficiente con discretización adaptativa
   En MATLAB:
   En Python:





   15

   Análisis de sistemas dinámicos en tiempo continuo
   Condición de punto fijo:


   dx
   ⇤
   = G(x ) = 0
   dt

   Ejemplo 1: modelo logistico continuo
   Puntos fijos
   Ejemplo 2: modelo Lotka-Volterra

   Puntos fijos





   Ejemplo: Contagio de enfermedades
   (epidemias y pandemias)
   Modelo matemático SIR (contagio entre personas)
   Variables
   Ecuaciones
   S(t): Susceptibles
   diferenciales
   I(t): Infectados
   R(t): Recuperados
   Parámetros
   : Nro. de contacto

   : Duración de la enfermedad

   Simulaciones Runge-Kutta (1)

   Susceptibles
   Infectados

   Simulaciones Runge-Kutta (2)

   Susceptibles
   Infectados

   Simulaciones en Matlab (1)
   Código MATLAB: link Github

   Definición de Modelo SIR

   Método de Euler

   Simulaciones en Matlab (2)
   Código MATLAB: link Github

   Método de Runge Kutta Orden 4

   Simulaciones en Matlab (3)
   Ejemplo de código para la simulación modelo SIR

   Código MATLAB: link Github

   Casos de estudio más complejos
   • Propagación de Malaria
   “A Multipatch Malaria Model with Logistic Growth Populations”,
   Gao, D. and Ruan, S., SIAM J. App. Math., 72 (3), 2012.
   1. Vector de contagio = mosquito
   2. Se considera un modelo con ecuaciones diferenciales en
   multiples zonas geográficas (multipatch).
   3. Se estudian los efectos de las migraciones humanas.

   • Efectos de la vacunación en enfermedades
   “Rich Bifurcation Structure in a Two-Patch Vaccination Model
   ”, Knipl, D., Pilarczyk, P. and Rost, G. SIAM J. App. Dyn.
   Syst., 14 (2), 2015.
   1. Impacto de las migraciones entre grandes ciudades
   2. Distintos tipos de evolución dependiendo del parámetro de
   reproducción.
   3. El parámetro de reproducción se puede controlar con un
   plan de vacunación.

   Linearización de Sistemas No-Lineales



   23



   Linearización de Sistemas No-Lineales



   24



   Material de Lectura
   - Material de lectura (esta clase):
   Libros (Mínimo):
   [2] Introduction to the Modeling and Analysis of Complex Systems - Sayama, Cap
   5 y 6.

   Libros (opcional):
   [6] Programming for Computations – Python - Linge and Langtangen, Cap 4
   [10] Introduction to Computational Science_ Modeling and Simulation for the
   Sciences - Angela B. Shiflet, George W. Shiflet-(2014) , Cap 2,4 y 6
   [11] Dynamical Systems with Applications using MATLAB - Stephen Lynch (2014)
   [12] Essential Matlab for Engineers and Scientists - Brian Hahn and Dan Valentine
   (2013), Cap 12

   - Leer para la próxima clase:
   Libros (Mínimo):
   [2] Introduction to the Modeling and Analysis of Complex Systems - Sayama, Cap 8.

   Libros (opcional):
   [11] Dynamical Systems with Applications using MATLAB - Stephen Lynch (2014), Cap 3 y 13
 
 
 
 
