#+title:Simulación de eventos discretos y Teoría de colas

* Simulación de sistemas - Eventos discretos

** Programación orientada a actividades, eventos y procesos

   En el caso que el sistema esté evolucionando todo el tiempo:

   Tiempo continuo

   Tiempo discreto

   Hay casos en las que es irrelevante simular un sistema todo el tiempo. Por
   ejemplo, imaginemos el caso de un depósito (Warehouse) donde se despachan
   productos de acuerdo a pedidos que entran en cualquier momento y es necesario ir
   actualizando el stock de productos.

   Las variables (inventario) son DISCRETAS

   Las variables cambian cuando tiene lugar un EVENTO (despacho de producto,
   reposición de stock, etc.)

   Simulación con distintas ACTIVIDADES que se empiezan, se desarrollan y terminan
   (en paralelo)

** Software de Simulación

   SIMULA: Desarrollado en los años 1960’s en el Norwegian Computing Center en Oslo. Este
   lenguaje introdujo el concepto de programación orientada a objetos.

   General Purpose Simulation System (GPSS): Desarrollado por IBM en los años 1960’s.

   SOFWARE MODERNO DE SIMULACIÓN
   - Comsol Multiphysics
   - Matlab Simulink

   EN ESTE CURSO (clases prácticas):
   - Simpy: Simulación de sistemas con eventos discretos y colas.

* Teoría de colas
** Introducción

   Recursos limitados (computadoras, sistemas de comunicaciones, etc.)  compartidos
   en una comunidad de usuarios.

   Los usuarios solicitan acceso a recursos en tiempos aleatorios.

   Uso del recurso durante un tiempo limitado aleatorio.

   Cuando el recurso esta ocupado el usuario permanece en una lista de espera
   (cola).

   TEORÍA DE COLAS permite estudiar estadísticamente el comportamiento de las
   listas de espera y uso de recursos compartidos, permitiendo cuantificar y
   optimizar: demoras, tiempos de proceso promedios, etc.

** Componentes de un sistema de colas



   - arrival times $S_1, S_2, S_3, \dots, S_i,\dots$, we denote the customer
     *arrival rate* by $\lambda$
   - a service that will require $\tau_i$ seconds of *service time* from one server
   - we will denote the rate at which customers are turned away by $\lambda_b$
   - service discipline: for example, First In, First Out (FIFO)
   - waiting time: from the arrival time of the i-th customer until the time it
     enters service.
   - service time $\tau_i$
   - total delay $T_i$

   $$T_i = W_i + \tau_i$$

** Motivación para el estudio de colas (I)

   Consider a system consisting of a single CPU that serves a queue of jobs in
   First-Come-First-Served (FCFS) order, as illustrated in Figure 1.2. The jobs
   arrive according to some random process with some average arrival rate, say
   $\lambda = 3$ jobs per second. Each job has some CPU service requirement, drawn
   independently from some distribution of jpb service requirements (we can assume
   any distribution on the job service requirements for this example). Let's say
   that the average service rate is $\mu = 5$ jobs per second (ie each job on the
   average requires 1/5 of a second of service). Note that the system is not in
   overload (3<5). Let *E*[T] denote the mean response time of this system, where
   *response time* is the time from when a job arrives until it completes service,
   aka sojour time.

   1.2.png

** Motivación para el estudio de colas (II)

   1.2

   Pregunta: Su jefe le dice a partir de mañana, la tasa de arrivos se
   duplicará. Debe comprar un CPU más rápido para que las tareas mantengan el
   tiempo de respuesta, E[T]. Esto es, los clientes no deberían notar el efecto del
   incremento de la tasa de arrivos. Por cuánto se debería incrementar la velocidad
   del CPU?
   1. Duplicar la velocidad del CPU
   2. Más del doble
   3. Ménos del doble

   La respuesta es 3 Ménos del doble

   Debemos desarrollar teoría basada en probabilidad para tomar decisiones con
   criterio científico

** Notación de Kendall a/b/m/K
   - a: Tipo de proceso de arribos
   - b: Distribución tiempo de servicio
   - m: Número de servers
   - K: Máximo número de clientes en el sistema

   - a = M: Poisson (iid exp.)
   - b =
     - M: iid exponencial
     - D: constante,
     - G: alguna distrib.

   Agner Krarup Erlang, un ingeniero danés, publicó un paper en 1909 introduciendo
   la teoría de colas aplicado a telefonía.

   M/D/1 (1917) y M/D/m (1920): modelado de sistema de telefonía

   2.png


   M/M/1


   M/M/m

** Fórmula de Little
   En el *estado estacionario*, el *número promedio de clientes* en el sistema
   es igual al producto de la *tasa de arribo promedio* y el *tiempo promedio en
   el sistema*.

   $$E[N] = \lambda E[t]$$

   3.png
   4.png

** Aplicaciones de la fórmula de Little (I)

Fabrica de semiconductores: Semiconductor devices are manufactured in extremely
capital-intensive fabrication facilities. The manufacturing process entails
starting with a silicon wafer and then building the electronic circuitry for
multiple identical devices through hundreds of process steps. Suppose that the
semiconductor factory starts 1000 wafers per day, on average; this is the input
rate. The start rate has remained fairly stable over the past 9 months. We track
the amount of work-in-process (WIP) inventory. The WIP varies between 40000 and
50000 wafers; the average WIP is 45000 wafers.

Then we can infer the average flow time in the factory. The arrival rate to the
factory is the wafer start rate: $\lambda = 1000$ wafers per day. The WIP is the
system queue length: $L=45000$ wafers. Thus the time or expected time in the
system is W=45 days. In a manufacturing context, we often refer to this as the
flow time, the time between when a job starts and finishes in a factory. For
instance, if we think of one wafer as being a job, then it takes the factory on
average 45 days to process it, that is to convert it from a blank wafer into a
finished wafer comprised of electronic devices. Knowing the flow time is
critical for planning and scheduling the factory, and for making delivery
commitments to customers. We shall return later to the connection between
Little's Law and operations management.

** Aplicaciones de la fórmula de Little (II)

email: Managing our email is a common and time consuming daily activity. For
many it is hard to keep up with the volume of messages, let alone provide timely
responses. A student Sue might recieve 50 messages each day to which she must
generate a response. Can we easily assess how well this student handles her
email duties?

Indeed we can apply Little's Law to get a quick sense of how promptly Sue
responds to messages. Suppose that she recieves about 50 messages every day;
then this is the arrival rate lambda = 50 . Suppose we can also track how many
messages have yet to be answered. For instance, suppose that Sue removes a
message from her inbox a~once she has responded to it. Then the remaining
messages in ther inbox are the messages that are waiting to be answered. Over
the last semester, the size of the inbox has varied between one and two hundred
messages with an average of 150 messages . Then we can regard this to be the
system queue length: L=150. From Little's Law we immediately have an estimate of
how long it takes Sue to answer a message, on average W=3 days

** Aplicaciones de la fórmula de Little (III)
** Aplicaciones de la fórmula de Little (IV)
** Aplicaciones de la fórmula de Little (V)

* Material de Lectura
  - [7] A Discrete-Event Simulation Course Based on the SimPy Language - Norm
    Matloff, University of California, 2011.
  - [15] Probability,_Statistics,_and_Random_Processes_for_Eletrical_Engineerging,
    3rd Ed Leon-Garcia, Cap. 12.
  - [8] https://simpy.readthedocs.io/en/latest/ (Simpy documentation)
  - [16]
    Performance-Modeling-and-Design-of-Computer-Systems-Queueing-Theory-in-Action,
    Caps. 1-2.
  - [17] Probability Statistics and Queueing Theory With Computer Science
    Applications-Arnold_O_Allen, Cap. 5.
 
 
