#+title:
Facultad de Ingeniería - Universidad de Buenos Aires Modelos y Simulación - 75.26/95.19 - Clase 15
Modelos y Simulación - 75.26/95.19
Clase 15: Unidad 4: 22-11-2019
Colas Multi-servers:
M/M/c, M/M/c/c y M/M/Infinito
1
Facultad de Ingeniería - Universidad de Buenos Aires Modelos y Simulación - 75.26/95.19 - Clase 15
Temas de hoy
• Colas M/M/c
• Colas M/M/c/c
• Colas M/M/Infinito
2
- Material de lectura (esta clase):
Libros (Mínimo):
[15] Probability,_Statistics,_and_Random_Processes_for_Eletrical_Engineerging, 3rd Ed
Leon-Garcia, Cap. 12.
Libros (opcional):
[16] Performance-Modeling-and-Design-of-Computer-Systems-Queueing-Theory-in-Action,
Caps. 1-2.
[17] Probability Statistics and Queueing Theory With Computer Science ApplicationsArnold_O_Allen, Cap. 5.
Repaso resultados
colas M/M/1
Facultad de Ingeniería - Universidad de Buenos Aires Modelos y Simulación - 75.26/95.19 - Clase 15
Colas M/M/1 4
Colas M/M/1 Colas M/M/1/K
Número de clientes: Número de clientes:
Tiempo en sistema: Tiempo en sistema:
Colas con múltiples
servidores (M/M/c)
Facultad de Ingeniería - Universidad de Buenos Aires Modelos y Simulación - 75.26/95.19 - Clase 15
 Colas M/M/c 6
Tasa de servicio de servidores en paralelo:
Es un caso particular de una cadena de Markov
de tipo birth-and-death process
Facultad de Ingeniería - Universidad de Buenos Aires Modelos y Simulación - 75.26/95.19 - Clase 15
7
Analicemos un proceso de birth-and-death en general
Estado estacionario de proceso birth-and-death
Ecuaciones de equilibrio:
Distribución de N(t)
en una cola M/M/c
Facultad de Ingeniería - Universidad de Buenos Aires Modelos y Simulación - 75.26/95.19 - Clase 15
9
Caso particular: cola M/M/c
Ecuaciones de equilibrio:
Facultad de Ingeniería - Universidad de Buenos Aires Modelos y Simulación - 75.26/95.19 - Clase 15
10 Análisis cola M/M/c
Probabilidad de que un cliente encuentre los servidores ocupados y tenga que
esperar en la cola:
Fórmula de
Erlang C
Número promedio de clientes en cola:
Tiempo promedio de espera en cola:
Fórmula de Little
Tiempo total en el sistema promedio:
Número promedio de clientes en el sistema:
Fórmula de Little
Facultad de Ingeniería - Universidad de Buenos Aires Modelos y Simulación - 75.26/95.19 - Clase 13
Ejemplo cola M/M/c 11
Facultad de Ingeniería - Universidad de Buenos Aires Modelos y Simulación - 75.26/95.19 - Clase 13
M/M/1 vs M/M/c 12
Comparar el delay y el tiempo de espera
promedios de los sistemas de la figura.
Notar que ambos tienen igual tasa de
servicio.
M/M/1
Increased
Waiting Time (W)
Decreased
Total Time (T)
M/M/c
Increased
Total Time (T)
Decreased
Waiting Time (W)
Distribución de T
en una cola M/M/c
Facultad de Ingeniería - Universidad de Buenos Aires Modelos y Simulación - 75.26/95.19 - Clase 13
Distribución del tiempo de espera en cola W (I) 14
Distribución geométrica
como en la M/M/1
Distribución Gamma
Facultad de Ingeniería - Universidad de Buenos Aires Modelos y Simulación - 75.26/95.19 - Clase 15
Distribución del tiempo de espera en cola W (II) 15
Ejercicio: demostrar esta ecuación usando propiedades de la suma de variables
independientes
Facultad de Ingeniería - Universidad de Buenos Aires Modelos y Simulación - 75.26/95.19 - Clase 15
Ejemplo cola M/M/c (cont.) 16
Colas M/M/c/c
Facultad de Ingeniería - Universidad de Buenos Aires Modelos y Simulación - 75.26/95.19 - Clase 15
Fórmula de Erlang B
Cola M/M/c/c 18
Ecuaciones de equilibrio:
Facultad de Ingeniería - Universidad de Buenos Aires Modelos y Simulación - 75.26/95.19 - Clase 15
Ejemplo cola M/M/c/c 19
Colas M/M/∞
Facultad de Ingeniería - Universidad de Buenos Aires Modelos y Simulación - 75.26/95.19 - Clase 15
Cola M/M/Infinito 21
Facultad de Ingeniería - Universidad de Buenos Aires Modelos y Simulación - 75.26/95.19 - Clase 15
Ejemplo cola M/M/Infinito 22
Material de Lectura
- Leer para la próxima clase:
Libros (Mínimo):
[15] Probability,_Statistics,_and_Random_Processes_for_Eletrical_Engineerging, 3rd Ed Leon-Garcia,
Cap. 12.
Libros (opcional):
[16] Performance-Modeling-and-Design-of-Computer-Systems-Queueing-Theory-in-Action, Caps. 1-2.
[17] Probability Statistics and Queueing Theory With Computer Science Applications-Arnold_O_Allen,
Cap. 5.
- Material de lectura (esta clase):
Libros (Mínimo):
[15] Probability,_Statistics,_and_Random_Processes_for_Eletrical_Engineerging,
3rd Ed Leon-Garcia, Cap. 12.
Libros (opcional):
[16] Performance-Modeling-and-Design-of-Computer-Systems-QueueingTheory-in-Action, Caps. 1-2.
[17] Probability Statistics and Queueing Theory With Computer Science
Applications-Arnold_O_Allen, Cap. 5.


 
 
 
