#+title:Ensayos Bernoulli
* Ensayos Bernoulli
Se trata de ensayos repetidos en forma independiente en los que hay
sólo dos resultados posibles, usualmente denominados /"éxito"/y
/"fracaso'', cuyas probabilidades, p y 1 − p, se mantienen constantes
a lo largo de todos los ensayos.  El espacio muestral de cada ensayo
individual está formado por dos puntos S y F . El espacio muestral de
n ensayos Bernoulli contiene 2 n

puntos o secuencias de n símbolos S y F , cada punto representa un
resultado posible del experimento compuesto. Como los ensayos} son
independientes las probabilidades se multiplican. En otras palabras,
la probabilidad de cada sucesión particular es el producto que se
obtiene reemplazando los símbolo s S y F por p y 1 − p,
respectivamente. Así,

\mathbb{P}(SSF SF \dots F F S) = pp(1 − p)p(1 − p)  \cdots  (1 − p)(1 − p)p.
**** Ejemplo 1.1. 
Si repetimos en forma independiente un experimento aleatorio y estamos
in teresados en la ocurrencia del evento A al que consideramos
/"éxito'', tenemos ensayos Bernoulli con p = \mathbb{P}(A).

**** Modelando ensayos Bernoulli. 
Los ensayos Bernoulli (con probabilidad de éxito p) se describen
mediante una sucesión de variables aleatorias independientes e
idénticamente distribuidas $(X_i: i \in N )$ cada una con distribución
$Bernoulli(p)$,

\mathbb{P}(X}
i
= x
i
) = p
x
i
(1 − p)
1{−x}
i
, x
i
\in \{0, 1}\. (1)}
Esto es, \mathbb{P}(X
i
= 1) = p y \mathbb{P}(X
i
= 0) = 1 − p}. En este contexto, X
i
= 1 significa que /"el}
resultado del i-ésimo ensayo es éxito''.

**** Preguntas elementales. 
Se pueden formular varios tipos de preguntas relacionadas con los
ensayos Bernoulli. Las más sencillas son las siguientes:
1. ¿Cuál es la cantidad total de éxitos en los primeros n ensayos?
2. ¿En n ensayos, cuál es el número de éxitos más probable?
3. ¿Cuánto /"tiempo"/hay que esperar para observar el primer éxito?
4. ¿Cuánto /"tiempo"/hay que esperar para observar el k-ésimo éxito?

En lo que sigue expresaremos las preguntas (a)-(d) en términos de las variables aleatorias
X
i
, i \geq 1, que describen los ensayos Bernoulli.

La cantidad de éxitos en los primeros n ensayos se describe mediante
la suma de las primeras variables X_1, \dots , X_n

S_n
:=
n
X
{i=1}
X
i
. (2)
3
La pregunta (a) interroga por la distribución de probabilidades de la variable aleatoria
S_n
definida en (2). Esto es, para cada k = 0, \dots , n, se trata de determinar cuánto valen
las probabilidades \mathbb{P}(S_n
= k). En cambio, la pregunta (b) interroga por el valor de k que
maximiza a la función de k, \mathbb{P}(S_n
= k).
El tiempo de espera hasta el primer é xito se describe mediante la variable aleatoria
T_1
:= mín\{i \in N : X
i
= 1{\, (3)
y en general, el tiempo de espera h ast a el k-ésimo éxito, k \geq 1 se describe, recursivamente,
mediante
T
k
:= mín\{i > T
k{−{1
: X
i
= 1{\. (4)
La pregunta (c) interroga por la distribución de probabilidades de la variable T}
1
definida en
(3): cuánto valen las probabilidades \mathbb{P}(T}
1
= n), n \in N ? Finalmente, la pregunta (d) interroga
por la distribución de probabilidades de las variables T}
k
, k \geq 2, definidas en (4): cuánto valen
las probabilidades \mathbb{P}(T}
k
= n), n \geq k}?
** La distribución binomial: cantidad de éxitos en n ensayos
La cantidad de éxitos puede ser 0, 1, \dots , n. El primer problema es
determinar las corre spondientes probabilidades. El evento en n
ensayos resultaron k éxitos y n − k fra casos

(
(X_1
, \dots , X
n
) = (x
1
, \dots , x
n
) :
n
X
{i=1}
x
i
= k
)
puede ocurrir de tantas formas distintas como k símbolos 1 se puedan ubicar en n lugares.
En otras palabras, el evento considerado contiene

n
k

puntos, cada uno de probabilidad
P
n
 \setminus 
{i=1}
\{X
i
= x
i
\}
!
=
n
Y
{i=1}
p
x
i
(1 − p)
1{−x}
i
= p
P
n
{i=1}
x
i
(1 − p)
n{−}
P
n
{i=1}
x
i
= p
k
(1 − p)
n{−}k
.
Por lo tanto,
\mathbb{P}(S_n
= k) =

n
k

p
k
(1 − p)
n{−}k
0 \leq k \leq n. (5)
En particular, la probabilidad de que no ocurra ningún éxito en n ensayos es (1 − p)
n
y la
probabilidad de que ocurra al menos un éxito es 1 − (1 − p)
n
.

La distribución de $S_n$, determinada en (5), se denomina la
distribución binomial de parámetros n y p y se denota Binomial(n, p).
**** Nota Bene 
Por definición, la distribución binomial de parámetros n y p es la
distribución de una suma de n variables aleatorias independientes cada
con distribución Bernoulli de parámetro p.

**** Ejemplo 1.2
Se tira un dado equilibrado 11 veces y en cada tiro se apuesta al 6,
¿cuál es la probabilidad de ganar exactamente 2 veces? Como el dado es
equilibrado, la probabilidad de éxito es 1 / 6 y la cantidad de éxitos
en 11 tiros tiene distribución Binomial (11, 1 / 6). Por lo tanto, la
probabilidad requerida es

  11 2  1 6  2  5 6  9 = 0.2960 \dots
**** Ejemplo 1.3
Cada artículo producido por una máquina será defectuoso con
probabilidad 0.1, independientemente de los demás. En una muestra de
3, ¿cuál es la probabilidad de encontrar a lo sumo un defectuoso?

Si X es la cantidad de artículos defectuosos en la muestra, entonces
$X \sim Binomial(3, 0.1)$.  En consecuencia,

\mathbb{P}(X \leq 1) = \mathbb{P}(X = 0) + \mathbb{P}(X = 1) =}

3
0

(0.1)
0
(0.9)
3
+

3
1

(0.1)
1
(0.9)
2
= 0.972.
**** Ejemplo 1.4. 
Un avión se mantendrá en vuelo mientras funcionen al menos el 50 % de
sus} motores. Si cada motor del avión en vuelo puede fallar con
probabilidad 1 − p independien temente de los demás, ¿para cuáles
valores de p \in (0, 1) es más seguro un avión de 4 motores que uno de
2?

Como cada motor puede fallar o funcionar independientemente de los
demás, la cantidad de motores que siguen funcionando es una variable
aleatoria con distribución binomial. La probabilidad de que un avión
de 4 motores realice un vuelo exitoso es


4
2

p
2
(1 − p)
2
+

4
3

p
3
(1 − p) +

4
4

p
4
= 6p
2
(1 − p)
2
+ 4p
3
(1 − p) + p
4
,
mientras que la correspondiente probabilidad para un avión de 2 motores es

2
1

p(1 − p) +}

2
2

p
2
= 2p(1 − p) + p
2
.
En consecuencia, el avión de 4 motores es más seguro que el de 2 si
6p
2
(1 − p)
2
+ 4p
3
(1 − p) + p
4
> 2}p(1 − p) + p
2
lo que es equivalente a las siguientes expresiones simplificadas
3p
3
− 8p}
2
+ 7{p − 2 > 0 \iff 3(p − 2 / 3)(p − 1)}
2
> 0 \iff p > 2}/{3}. 
Por lo tanto, el avión de 4 motores es más seguro cuando la probabilidad de que cada motor
se mantenga en funcionamiento es mayor que 2 / 3, mientras que el avión de 2 motores es más
seguro cuando esa probabilidad es menor que 2 / 3.
**** Ejemplo 1.5. 
Si la probabilidad de éxito es p = 0.01, cuántos ensayos se deb en realizar para}
asegurar que la probabilidad de que ocurra por lo menos un éxito sea al menos 1 /}2?
Buscamos el menor entero n tal que 1 − (0.99)
n
\geq
1
2
, o equivalentemente
1
2
\geq (0.99)
n
.
Tomando logaritmos − log 2 \geq n log(0.99) y despejando n resulta n \geq − log(2)/ log(0.99) \approx}
68.96. Por lo tanto, n = 69.
5
** Término central
De la fórmula (5) se puede ver que
\mathbb{P}(S_n
= k)
\mathbb{P}(S_n
= k − 1)
=

n
k

p
k
(1 − p)
n{−}k

n
k{−{1

p
k{−{1
(1 − p)
n{−}{k+1}
=
(k − 1)!(n − k + 1)!p
k{!(n − k)!(1 − p ) 
=
(n − k + 1)p
k(1 − p ) 
= 1 +
(n + 1)p − k}
k(1 − p ) 
. (6)
De (6) se deduce que \mathbb{P}(S_n
= k) crece cuando k < (n + 1)p y decrece cuando k > (n + 1)p. Si
(n + 1)p es un número entero, entonces \mathbb{P}(S_n
= (n + 1)p) = \mathbb{P}(S_n
= (n + 1)p − 1). En otras
palabras, la cantidad más probable de éxitos en n ensayos es m := [(n + 1)p]. Salvo e
n el caso
en que m = (n + 1)p, donde también lo es m − 1.
Cuando p =
1
2
el resultado anterior se puede observar directamente en el triángulo de
Pascal: en el centro de las filas pares está el máximo. En la región central de las filas impares
hay dos máximos.
**** Ejemplo 1.6. 
Se tira un dado equilibrado n veces y en cada tiro se apuesta al 6. ¿Cuál es la}
cantidad más probable de éxitos cuando n = 12? y cuando n = 11?
La cantidad de éxitos tiene distribución Binomial (n, p), donde p = 1 / 6. Cuando n = 12,
(n + 1)p = 13 / 6 = 2.16... y entonces la cantidad más probable de éxitos es m = 2. Cuando
n = 11, (n + 1)p = 2 y entonces la cantidad más probable de éxitos es m = 1 o m = 2.
** La distribución geométrica: tiempo de espera hasta el primer éxito
El tiempo que hay que esperar para observar el primer éxito en una sucesión de ensayos
Bernoulli puede ser n = 1, 2, \dots . El evento T}
1
= 1 significa que se obtuvo éxito en el primer
ensayo y tiene probabilidad p. Para cada n \geq 2, el evento T}
1
= n significa que en los primeros
n − 1 ensayos se obtuvieron fracasos y que en el n-ésimo se obtuvo éxito, lo que tiene proba}
bilidad (1 − p)
n{−{1
p. Por lo tanto, la distribución de T_1
es
\mathbb{P}(T_1
= n) = (1 − p)
n{−{1
p, n \in N} . (7)
El evento T}
1
> n significa que los primeros n ensayos de la sucesión resultaron fracaso. Por}
lo tanto,
\mathbb{P}(T_1
> n) = (1 − p ) 
n
, n \geq 1} . (8)
La distribución de T}
1
se denomina distribución geométrica de parámetro p y se designa me- 
diante Geométrica(p).
**** Ejemplo 1.7. 
Se arroja repetidamente un dado equilibrado. ¿Cuál es la probabilidad de}
que el primer 6 aparezca antes del quinto tiro?. La probabilidad de obtener 6 es 1 / 6 y la
cantidad de tiros hasta obtener el primer as tiene distribución Geométrica(1 / 6). Por lo tanto,
la probabilidad requerida es
1 / 6 + (5 / 6)(1 / 6) + (5 / 6)
2
(1 / 6) + (5 / 6)
3
(1 / 6) = (1 / 6)

1 − (5 / 6)
4
1 − (5 / 6)

= 1 − (5 / 6)
4
= 0.5177 \dots}
6
**** Ejemplo 1.8 (Ocurrencias casi seguras). 
Si al realizarse un experimento aleatorio un evento
A tiene probabilidad positiva de ocurrir, entonces en una sucesión de experimentos indepen
dientes el evento A ocurrirá casi seguramente.
En efecto, el tiempo de espera hasta que ocurra el evento A es una variable aleatoria T}
A
con distribución geométrica de parámetro p = \mathbb{P}(A). Si se observa que
\{T}
A
> 1{\} ⊇ \}T
A
> 2{\} ⊇ \}T
A
> 3{\} ⊇  \cdots 
y que
\{T}
A
= \infty\} =
 \setminus 
n \geq 1
\{T}
A
> n{\}
y se usa la propiedad de continuidad de P, se obtiene que
\mathbb{P}(T
A
= \infty) = P


 \setminus 
n \geq 1
\{T}
A
> n{\}


= \lim_{n  \rightarrow \infty}
\mathbb{P}(T
A
> n) = lím}
{n \rightarrow \infty}
(1 − p)
n
= 0.
Por lo tanto, \mathbb{P}(T}
A
< \infty) = 1.}
Pérdida de memoria
La variable aleatoria, T , con distribución geométrica de paráme tro p tiene la propiedad
de pérdida de memoria, 
\mathbb{P}(T > n + m | T > n) = \mathbb{P}(T > m) n, m \in N (9)
La identidad (9) se obtiene de (8) y de la fórmula de probabilidad condicional:
\mathbb{P}(T > n + m | T > n) =}
\mathbb{P}(T > n + m, T > n)
\mathbb{P}(T > n)
=
\mathbb{P}(T > n + m)
\mathbb{P}(T > n)
=
(1 − p)
n{+}m
(1 − p)
n
= (1 − p)
m
= \mathbb{P}(T > m).
De hecho, la propiedad de pérdida de memoria definida en (9) caracteriza a la distribución
geométrica.
**** Teorema 1.9. 
Si T es una variable aleatoria a valores en N con la propiedad de pérdida de}
memoria, entonces T \sim Geométrica(p), donde p = \mathbb{P}(T = 1).
**** Demostración 
Sea G(n) := \mathbb{P}(T > n). Si T pierde memoria, tenemos que}
G ( n + m) = G ( n ) G ( m) (10)
De (10) sigue que G(2) = G(1)G(1) = G(1)
2
, G(3) = G(2)G(1) = G(1)
3
y en general
G ( n) = G(1)
n
cualquiera sea n \in N . En otros términos, la distribución de T es tal que
\mathbb{P}(T > n) = G(1)
n
.
Por lo tanto,
\mathbb{P}(T = n) = \mathbb{P}(T > n − 1) − \mathbb{P}(T > n ) = G(1)
n{−{1
− G(1)}
n
= G(1)
n{−{1
(1 − G}(1)).
7
** La distribución Pascal: tiempo de espera hasta el k-ésimo éxito
Si se quieren observar k-éxitos en una sucesión de ensayos Bernoulli lo mínimo que se
debe esperar es k ensayos. ¿Cuándo ocurre el evento T}
k
= n, n \geq k}? El n-ésimo ensayo debe
ser éxito y en los n − 1 ensayos anteriores deben oc urrir exactamente k − 1 éxitos. Hay

n{−{1
k{−{1

formas distintas de ubicar k − 1 símbolos 1 en n − 1 lugares. Por lo tanto,
\mathbb{P}(T
k
= n) =

n − 1
k − 1

p
k
(1 − p)
n{−}k
n \geq k. (11)
La distribución de T}
k
se denomina distribución Pascal de parámetros k y p y se designa 
mediante Pascal(k, p).
La dist ribu ción Pascal de parámetros k y p es la distribución de una suma de k variables
aleatorias independientes cada una con ley Geométrica(p). Lo cual es intuitivamente claro si}
se piensa en el modo que arribamos a su definición.
En efecto, definiendo T}
0
:= 0 vale que
T
k
=
k
X
{i=1}
(T}
i
− T}
{i-1}
).
Basta ver que para cada i = 1, \dots , k las diferencias T}
i
− T}
{i-1}
son independientes y todas se
distribuyen como T}
1
\sim Geométrica(p). De acuerdo con la regla del producto}
P

\cap
k
{i=1}
\{T}
i
− T}
{i-1}
= m
i
\}

= \mathbb{P}(T}
1
= m
1
)
\times
n{−{1
Y
{i=2}
P

T
i
− T}
{i-1}
= m
i
| \cap
{i-1}
{j=1}
\{T}
j
− T}
j{−{1
= m
j
\}

. (12)
Si se sabe que T}
1
= m
1
, \dots , T
{i-1}
− T}
i{−{2
= m
{i-1}
, entonces el evento T}
i
− T}
{i-1}
= m
i
depende
las variables aleatorias X
P
{i-1}
{j=1}
m
j
+1
, \dots , X
P
i
{j=1}
m
j
y equivale a decir que las primer as m
i
− 1}
de esas variables valen 0 y la última vale 1. En consecuencia,
P

T
i
− T}
{i-1}
= m
i
| \cap
{i-1}
{j=1}
\{T}
j
− T}
j{−{1
= m
j
\}

= (1 − p)
m
i
−{1}
p. (13)
De (12) y (13) se deduce que
P

\cap
k
{i=1}
\{T}
i
− T}
{i-1}
= m
i
\}

=
k
Y
{i=1}
(1 − p)
m
i
−{1}
p. (14)
De la factorización (14) se deduce que T}
1
, T_2
− T}
1
, \dots , T
k
− T}
k{−{1
son independientes y que
cada una tiene distribución geométrica de parámetro p.
**** Ejemplo 1.10. 
Lucas y Monk disputan la final de un campeonato de ajedrez. El primero}
que gane 6 partidas (no hay tablas) resulta ganador. La probabilidad de que Lucas gane
cada partida es 3 / 4. ¿Cuál es la probabilidad de que Lucas gane el campeonato en la novena
partida? La cantidad de partidas que deben jugarse hasta que Lucas gane el campeonato tiene
distribución Pascal(6, 3 / 4). Por lo tanto, la probabilidad requerida es

8
5

3
4

6

1
4

3
= 0.1557 \dots}
8
**** Ejemplo 1.11. 
En una calle hay tres parquímetros desocupados. Se estima que en los próxi
mos 10 minutos pasarán 6 coches por esa calle y, en media, el 80 % tendrá que estacionarse
en alguno de ellos. Calcular la probabilidad de que los tres parquímetros sean ocupados en
los próximos 10 minutos.
La probabilidad requerida es la probabilidad de que la cantidad, N, de ensayos hasta el
tercer éxito sea menor o igual que 6. Como N tiene distribución Pascal(3, 0.8) resulta que
\mathbb{P}(N \leq 6) =}
6
X
{n=3}
\mathbb{P}(N = n) =}
6
X
{n=3}

n − 1
2

(0.8)
3
(0.2)
n{−{3
= (0.8)
3

2
2

(0.2)
0
+

3
2

(0.2)
1
+

4
2

(0.2)
2
+

5
2

(0.2)
3

= (0.8)
3

1 + 3(0.2) + 6(0.2)
2
+ 10(0.2)
3

= 0.983 \dots}
Notar que una forma alternativa de obtener el mismo resultado es sumar las probabilidades
de observar 3, 4, 5, 6 éxitos en 6 ensayos Bernoulli.
Relación entre las distribuciones B inomial y Pascal. Sean S_n
\sim Binomial(n, p) y}
T
k
\sim Pascal(k, p). Vale que}
\mathbb{P}(S_n
\geq k) = \mathbb{P}(T}
k
\leq n ) . (15)}
En efecto, decir que en n ensayos Bernoulli ocurren por lo menos k éxitos es l o mismo que
decir que el tiempo de espera hasta observar el k-ésimo éxito no supera a n.
** La distribución multinomial
La distribución binomial se puede generalizar al caso de n ensayos independientes donde
cada ensayo puede tomar uno de varios resultados. Sean 1, 2, \dots , r los resultados posibles de
cada ensayo y supongamos que para cada k \in \}1, 2, \dots , r{\} la probabilidad p
k
de observar el
valor k se mantiene constante a lo largo de los ensayos. La pregunta es: ¿Cuántas veces o curre
cada uno de los resultados en los primeros n ensayos?
Consideramos una sucesión X_1
, X_2
, \dots de variables aleatorias independientes e idénti
camente distribuidas a valores \1, 2, \dots , r{\} tal que \mathbb{P}(X
i
= k) = p
k
. Fijado n, para cada
k = 1, \dots , r definimos la variables M
k
=
P
n
{i=1}
1\{X}
i
= k{\} . La variable M}
k
cuenta la cantidad
de veces que ocurre el resultado k en n ensayos. La probabilidad de que en n ensayos el
resultado 1 ocurra m
1
veces, el resultado 2 ocurra m
2
veces, etc. es
\mathbb{P}(M
1
= m
1
, M
2
= m
2
, \dots , M
r
= m
r
) =
n{!}
m
1
!m
2
!  \cdots  m}
r
!
p
m
1
1
p
m
2
2
 \cdots  p
m
r
r
, (16)
donde los m
k
son enteros no negativos sujetos a la condición m
1
+ m
2
+  \cdots  + m
r
= n.
Si r = 2, entonces (16) se reduce a la distribución Binomial con p
1
= p, p
2
= 1 − p, k
1
= k
y k
2
= n − k .
9
\hypertarget{pfa}
** j Miscelánea de ejemplos
**** Observación 1.12 (Desarrollo de Taylor). 
Para todo x \in (0, 1) vale que}
1
(1 − x)
{k+1}
=
X
n \geq 0

n + k
k

x
n
. (17)
La identidad (17) se obtiene desarrollando la función h(x) = (1 − x)
−(k+1)
en serie de
Taylor alrededor del 0: observando que h
(n)
(0) = (k + 1)(k + 2)  \cdots  (k + n), se obtiene que
h
(n)
(0)
n{!}
=

n{+}k
k

.
**** Ejemplo 1.13 
(Variable compuesta). Sean N
1
; X_1
, X_2
, \dots una sucesión de variables aleato
rias independientes. Supongamos que N}
1
\sim Geométrica(p}
1
) y que X
i
\sim Bernoulli(p}
2
), i \geq 1.
Entonces,
N
2
=
N
1
−{1}
X
{i=1}
X
i
\sim Geométrica}

p
1
p
1
+ p
2
(1 − p}
1
)

− 1. (18)
Por definición N}
2
|{N}
1
= n \sim Binomial(n − 1, p}
2
). Aplicando la fórmula de probabilidad total
obtenemos
\mathbb{P}(N
2
= k) =
X
n \geq 1
\mathbb{P}(N
2
= k | N}
1
= n)\mathbb{P}(N}
1
= n)
=
X
n \geq {k+1}

n − 1
k

p
k
2
(1 − p}
2
)
n{−{1}−}k
(1 − p}
1
)
n{−{1
p
1
=
X
m \geq 0

m + k
k

p
k
2
(1 − p}
2
)
m
(1 − p}
1
)
m{+}k
p
1
= (p
2
(1 − p}
1
))
k
p
1
X
m \geq 0

n + k
k

[(1 − p}
1
)(1 − p}
2
)]
m
. (19)
Usando (17) vemos que
X
m \geq 0

m + k
k

[(1 − p}
1
)(1 − p}
2
)]
m
=
1
(1 − (1 − p}
1
)(1 − p}
2
))
{k+1}
=
1
(p
1
+ p
2
(1 − p}
1
))
{k+1}
. (20)
Combinando (19) y (20) obtenemos que
\mathbb{P}(N
2
= k) =
(p
2
(1 − p}
1
))
k
p
1
(p
1
+ p
2
(1 − p}
1
))
{k+1}
=

p
2
(1 − p}
1
)
p
1
+ p
2
(1 − p}
1
)

k

p
1
p
1
+ p
2
(1 − p}
1
)

. (21)
**** Ejemplo 1.14 
(Rachas). Para cada número entero m > 1 sea Y}
m
la cantidad de ensayos
Bernoulli(p) que se deben realizar hasta obtener por primera vez una r acha de m éxitos segui- 
dos. En lo que sigue vamos a calcular E[Y
m
] mediante condicionales. Para ello introducimos
10
\hypertarget{pfb}
una variable aleatoria auxiliar N que cuenta la cantidad de ensayos que deben realizarse hasta
obtener por primera vez un fracaso y usaremos la identidad E[Y
m
] = E[E[Y
m
|{N]].}
Observando que
Y
m
|{N = n \sim

n + Y
m
si n \leq m,}
m si n > m,
obtenemos la expresión de la función de regresión
\varphi ( n) = E[Y
m
|{N = n ] =

n + E[Y
m
] si n \leq m,}
m si n > m.
En consecuencia, E[Y
m
|{N] = N{1} \{N \leq m\} + E[Y}
m
]1\{N \leq m\} + m{1{\}N > m{\}, de donde se
deduce que E[Y
m
] = E[N{1{\}N \leq m{\] + E[Y
m
]\mathbb{P}(N \leq m) + m\mathbb{P}(N > m). Equivalentemente,
E[Y}
m
] =
E[N{1{\}N \leq m{\]
\mathbb{P}(N > m)
+ m. (22)
Debido a que N 1{\}N \leq m{\} = N − N{1{\}N > m{\} el primer término del lado derecho de la
igualdad (22) se puede expresar de siguiente forma
E[N{1{\}N \leq m{\]
\mathbb{P}(N > m)
=
E[N] − E[N 1{\}N > m{\]
\mathbb{P}(N > m)
=
E[N]
\mathbb{P}(N > m)
− E[N |{N > m]
=
E[N]
\mathbb{P}(N > m)
− E[N ] − m. (23)}
La última igualdad se deduce de la propiedad de pérdida de memoria de la distribución
Geométrica. De N | N > m \sim m + N, resulta que E[N | N > m] = m + E[N].
Combinando (22) y (23) obtenemos
E[Y}
m
] =
E[N]
\mathbb{P}(N > m)
− E[N ] =
E[N]\mathbb{P}(N \leq m)
\mathbb{P}(N > m)
=
1 − p}
m
(1 − p)p
m
. (24)
**** Ejemplo 1.15 
(Coleccionista I). Sea M una variable aleatoria a valores 1, 2, \dots , m}. Sea}
(M}
n
: n \in N ) una sucesión de variables aleatorias i ndependientes tal que M}
n
\sim M para
todo n \in N . Sea K = mín\{n \geq m : \{M
1
, \dots , M
n
\} = \{1, 2, \dots , m}\}\} el tamaño de muestra}
mínimo que se necesita para /"coleccionar"/todos los valores 1, 2, \dots , m}. En lo que sigue vamos
a calcular E[K] mediante condicionales. Introducimos un elemento aleatorio C que indica el
orden en que se obtuvieron los valores 1, 2, \dots , m y usamos la identidad E[K] = E[E[K | C]].
Sea S(m) al conjunto de todas las permutaciones de los números 1, 2, \dots , m}. Para cada
permutación \sigma = ( \sigma 
1
, \sigma
2
, \dots , \sigma
m
) \in S}(m) vale que:
\mathbb{P}(C = \sigma) =}
m{−{1
Y
{k=1}
\mathbb{P}(M = \sigma
k
)
P
m
{i=k}
\mathbb{P}(M = \sigma
i
)
.
Por otra parte
K | C = \sigma \sim 1 +
m{−{1
X
{k=1}
N ( \sigma
i
: 1 \leq 1 \leq k), 
11
\hypertarget{pfc}
donde N( \sigma 
i
: 1 \leq i \leq k) \sim Geométrica

P
m
{i=k+1}
\mathbb{P}(M = \sigma
i
)

. Por lo tanto,
E[K] =}
X
{\sigma \in S(m)}
E[K | C = \sigma]\mathbb{P}(C = \sigma)
=
X
{\sigma \in S(m)}
1 +
m{−{1
X
{k=1}
1
P
m
{i=k+1}
\mathbb{P}(M = \sigma
i
)
!
m{−{1
Y
{k=1}
\mathbb{P}(M = \sigma
k
)
P
m
{i=k}
\mathbb{P}(M = \sigma
i
)
. (25)
En el caso particular en que \mathbb{P}(M = i) = 1{/m para todo i \in \}1, 2, \dots , m{\} tenemos que
E[K] =}
X
{\sigma \in S(m)}
1 +
m{−{1
X
{k=1}
1
P
m
{i=k+1}
1{/m}
!
m{−{1
Y
{k=1}
1{/m}
P
m
{i=k}
1{/m}
= m!
1 +
m{−{1
X
{k=1}
1
P
m
{i=k+1}
1{/m}
!
1
m{!}
=
m{−{1
X
{k=0}
1
P
m
{i=k+1}
1{/m}
= m
m
X
{i=1}
1
i
. (26)
**** Ejemplo 1.16 
(Coleccionista II). Sea X}
1
, X_2
, \dots una sucesión de variables aleatorias inde
pendientes e idénticamente distribuidas a valores 1, 2, \dots , r}. Sea N}
r
= mín\{n \geq 1 : X
n
= r{\} .
Para cada i = 1, \dots , r − 1 sea M}
i
=
P
N
r
−{1}
{n=1}
1\{X}
n
= i{\} . Queremos hallar la función de
probabilidad de M}
i
.
Por definición N}
r
\sim Geométrica(p}
r
) y M}
i
|{N}
r
= n \sim Binomial

n − 1}, p
i
(1 − p}
r
)
−{1}

. De
acuerdo con el Ejemplo 1.13 
tenemos que
M
i
\sim Geométrica}

p
r
p
r
+ p
i
(1 − p}
r
)
−{1}
(1 − p}
r
)

− 1 = Geométrica}

p
r
p
r
+ p
i

− 1.
En particular, E[M}
i
] = p
i
/p
r
y V(M}
i
) = p
i
(p
r
+ p
i
)/p}
2
r
.
* La distribución de Poisson
** Motivación: Aproximación de Poisson de la distribución binomial
En diversas aplicaciones tenemos que tratar con ensayos Bernoulli donde, para decirlo
de algún modo, n es grande y p es pequeño, mientras que el producto \lambda = np es modera
do. En tales casos conviene usar una aproximación de las probabilidades \mathbb{P}(S_n
= k), donde
S_n
\sim{Binomial(n, p) y p = \lambda/n}. Para k = 0 tenemos}
\mathbb{P}(S_n
= 0) = (1 − p)
n
=

1 −}
\lambda
n

n
. (27)
Tomando logaritmos y usando el desarrollo de Taylor,
log(1 − t) = −t −}
1
2
t
2
−
1
3
t
3
−
1
4
t
4
−  \cdots  , 
se obtiene
log \mathbb{P}(S_n
= 0) = n log

1 −}
\lambda
n

= −{\lambda −}
\lambda
2
2n
−  \cdots  (28)
12
\hypertarget{pfd}
En consecuencia, para n grande se tiene que
\mathbb{P}(S_n
= 0) \approx e}
− \lambda 
, (29)
donde el signo \approx se usa para indicar una igualdad aproximada (en este caso de orden de
magnitud 1{/n). Más aún, usando la identidad (6) se puede ver que para cada k fijo y n
suficientemente grande
\mathbb{P}(S_n
= k)
\mathbb{P}(S_n
= k − 1)
=
(n − k + 1)p
k(1 − p ) 
\approx
\lambda
k
. (30)
Recursivamente se concluye que
\mathbb{P}(S_n
= 1) \approx \lambda · \mathbb{P}(S_n
= 0) \approx \lambda e
− \lambda 
,
\mathbb{P}(S_n
= 2) \approx}
\lambda
2
· \mathbb{P}(S 
n
= 1) \approx}
\lambda
2
2
e
− \lambda 
,
y en general
\mathbb{P}(S_n
= k) \approx}
\lambda
k
k{!}
e
− \lambda 
. (31)
La igualdad aproximada (31) se llama la apro
ximación de Poisson de la distribución binomial.
0 2 4 6 8 10
0
0.05
0.1
0.15
0.2
0.25
0.3
0.35
Figura 1: Comparación. Funciones de probabilidad de las distribuciones Binomial(10, 1 / 5)
(bolita negra) y Poisson(2) (cuadradillo vacío).
Otro modo de obtener el mismo resultado.
\mathbb{P}(S_n
= k) =

n
k

p
k
(1 − p)
n{−}k
\sim
1
k{!}

np
1 − p}

k
(1 − p)
n{−}k
\rightarrow
\lambda
k
k{!}
e
− \lambda 
.
13
\hypertarget{pfe}
**** Ejemplo 2.1 (Artículos defectuosos)
Una industria produce tornillos. Supongamos que la}
probabilidad de que un tornillo resulte defectuoso se a p = 0.015, entonces la probabilidad de
que una caja de 100 tornillos no contenga ninguno defectuoso es (0.985)
100
= 0.2206... La
aproximación de Poisson es e
−{1.5}
= 0.2231... y es suficientemente próx ima para la mayoría de
los propósitos prácticos. Si se pregunta: Cuántos tornillos debería contener la c aja para que la
probabilidad de encontrar al menos 100 tornillos sin defectos sea 0 .8 o mejor? Si 100 + x es el
número buscado, entonces x es un número pequeño. Para aplicar la aproximación de Poisson
para n = 100 + x ensayos debemos poner \lambda = np, pero np es aproximadamente 100p = 1.5.
Buscamos el menor entero x para el cual
e
−{1.5}

1 +
1.5
1
+  \cdots }
(1.5)
x
x{!}

\geq 0.8 (32)
Para x = 1 el valor del lado izquierdo de la inecuación (32) es aproximadamente 0.558, para
x = 2 es aproximadamente 0.809. Por lo tanto, l
a aproximación de Poisson permite concluir}
que se necesitan 102 tornillos. En realidad la probabilidad de encontrar al menos 100 tornillos
sin defectos en una caja de 102 es 0.8022 \dots .
** La distribución Poisson
Sea \lambda > 0. Una variable aleatoria N tiene distribución Poisson( \lambda ) si sus posibles valores
son los enteros no negativos y si
\mathbb{P}(N = n) = e}
− \lambda 
\lambda
n
n{!}
, n = 0, 1, \dots (33)
Media y varianza. Usando el desarrollo de Taylor de la función exponencial e}
x
=
P
\infty
{n=0}
x
n
n{!}
se demuestra que E[N] = \lambda y V(N ) = \lambda}.
Aditividad. El rasgo más importante de la distribución Poisson es su aditividad.
**** Teorema 2.2 (Aditividad). Si N
1
y N}
2
son variables aleatorias independientes con distribu
ción Poisson de medias \lambda}
1
y \lambda}
2
, respectivamente. Entonces,
N
1
+ N}
2
\sim P oisson ( \lambda}
1
+ \lambda}
2
).
**** Demostración.
\mathbb{P}(N
1
+ N}
2
= n) =
n
X
{m=0}
\mathbb{P}(N
1
= m, N}
2
= n − m) =
n
X
{m=0}
\mathbb{P}(N
1
= m)\mathbb{P}(N}
2
= n − m)
=
n
X
{m=0}
e
− \lambda 
1
\lambda
m
1
m{!}
e
− \lambda 
2
\lambda
n{−}m
2
(n − m)!
=
e
−( \lambda }
1
+ \lambda 
2
)
n{!}
n
X
{m=0}

n
m

\lambda
m
1
\lambda
n{−}m
2
= e
−( \lambda }
1
+ \lambda 
2
)
( \lambda 
1
+ \lambda}
2
)
n
n{!}
.
14
\hypertarget{pff}
**** Nota Bene 
El resultado del Teorema 2.2 se extiende por inducción a la suma de una}
cantidad finita de variables aleatorias independientes con distribución Poisson.
**** Teorema 2.3 (Competencia). Sean N
1
, N
2
, \dots , N
m
variables aleatorias independientes, cada
N
j
con distribución Poisson de media \lambda}
j
, respectivamente. Sea S = N}
1
+  \cdots  + N}
m
. Entonces,
para cada n \geq 1 vale que
(N}
1
, N
2
, \dots , N
m
)|{S = n \sim Multinomial}

n,
\lambda
1
\lambda
,
\lambda
2
\lambda
, \dots ,
\lambda
m
\lambda

,
donde \lambda =
P
j
\lambda
j
. En particular,
\mathbb{P}(N
j
= 1{|{S = 1) =
\lambda
j
\lambda
.
**** Demostración 
La suma S = N
1
+{ \cdots }+{N}
m
tiene distribución Poisson de media \lambda =
P
j
\lambda
j
;
y entonces siempre que n
1
+  \cdots  + n
m
= n,
\mathbb{P}(N
1
= n
1
, \dots , N
m
= n
m
|{S = n) =
\mathbb{P}(N
1
= n
1
, \dots , N
m
= n
m
)
\mathbb{P}(S = n)
=
Y
j
e
− \lambda 
j
\lambda
n
j
j
n
j
!
!,

e
− \lambda 
\lambda
n
n{!}

=
n{!}
n
1
!n
2
!  \cdots  n}
m
!
Y
j

\lambda
j
\lambda

n
j
.
**** Nota Bene 
En el caso particular n = 2, el resultado del Teorema 2.3 se reduce a que,}
si N}
1
y N}
2
son variables aleatorias independientes con distribución Poisson de medias \lambda}
1
y
\lambda
2
, respectivamente, entonces, dado que N}
1
+ N}
2
= n, la distribución condicional de N}
1
es
Binomial(n, p), donde p =
\lambda
1
\lambda
1
+ \lambda 
2
.
**** Teorema 2.4 (Adelgazamiento). Sea N una variable aleatoria Poisson de media \lambda}. Sea M
una variable aleatoria tal que
M | N = n \sim Binomial ( n, p ) .
Entonces, M y N − M son variables aleatorias independientes con distribución Poisson de
medias p\lambda y (1 − p) \lambda , res pectivamente.
**** Demostración 
Sean m, k \geq 0}
\mathbb{P}(M = m, N − M = k) = \mathbb{P}(M = m, N − M = k | N = m + k)\mathbb{P}(N = m + k)
= \mathbb{P}(M = m | N = m + k)\mathbb{P}(N = m + k)
=

m + k
m

p
m
(1 − p)
k

e
− \lambda 
\lambda
m{+}k
(m + k)!
=

e
−{p\lambda}
(p\lambda)
m
m{!}

e
−(1}−{p ) \lambda}
((1 − p) \lambda )
k
k{!}

.
15
**** Ejercicios adicionales
1. Sea N una variable aleatoria con distribución Poisson de media \lambda}. Mostrar que}
\mathbb{P}(N = n) =}
\lambda
n
\mathbb{P}(N = n − 1), n = 1, 2, \dots
Usar ese resultado para encontrar el valor de n para el cual \mathbb{P}(N = n) es maximal.
2.

Se lanza una moneda una cantidad aleatoria N de veces, donde N tiene distribución
Poisson. Sean N}
1
y N}
2
la cantidad de total de caras y de cecas observadas, respectivamente.
Mostrar que las variables aleatorias N}
1
y N}
2
son independientes y que tienen distribución
Poisson.
3. Sea X}
1
, X_2
, \dots una sucesión de variables aleatorias independientes, cada una con distribu
ción Bernoulli(p). Para cada n \geq 1 se define S_n
:=
P
n
{i=1}
X
i
. Por convención, S}
0
:= 0. Sea N}
una variable aleatoria con distribución Poisson( \lambda ). Mostrar que S}
N
\sim Poisson(p\lambda).
** e La aproximación Poisson. (Técnica de acoplamiento)
En lo que sigue mostraremos que cuando se consideran una gran cantidad de eventos inde
pendientes y cada uno de ellos tiene una probabilidad muy pequeña de ocurrir, la cantidad de
tales eventos que realmente ocurre tiene una distribución /"cercana"/a la distribución Poisson.
0 0.5 1 1.5 2 2.5 3
0
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
Figura 2: Comparación de las funciones de probabilidad de las distribuciones Bernoulli(1 / 4)
(bolita negra) y Poisson(1 / 4) (cuadradillo vacío)
16
Construcción conjunta de variables Bernoulli y Poisson (Acoplamiento).
Para cada p \in [0, 1] dividimos el intervalo [0, 1) en dos intervalos
I
0
(p) = [0, 1 − p), I}
1
(p) = [1 − p, 1) (34)
y en la sucesión de intervalos
J
0
(p) = [0, e}
−p
), J}
k
(p) =


k{−{1
X
{j=0}
e
−p
p
k
k{!}
,
k
X
{j=0}
e
−p
p
k
k{!}


, k = 1, 2, \dots . (35)
Consideramos una variable aleatoria U con distribución U[0, 1) y construimos dos variables
aleatorias V y W con distribuciones Bernoulli(p) y Poisson(p), respectivamente:
V := 1{\}U \in I
1
(p)\, W :=
\infty
X
{k=0}
k{1{\}U \in J
k
(p)\. (36)
De la desigualdad 1 −p \leq e}
−p
resulta que I}
0
(p) \subset J
0
(p) y que J}
1
(p) \subset I
1
(p). En consecuencia,
V = W \iff U \in I
0
(p) \cup J
1
(p). Por ende,
\mathbb{P}(V = W ) = \mathbb{P}(U \in I
0
(p) \cup J
1
(p)) = 1 − p + e
−p
p, (37)
y en consecuencia,
\mathbb{P}(V \neq W ) = p − e
−p
p = p(1 − e
−p
) \leq p}
2
. (38)
Usando la desigualdad (38) pueden obtenerse las siguientes cotas:
sup
k \geq 0
|{\mathbb{P}(V = k) − \mathbb{P}(W = k)}| \leq p
2
, (39)
X
k
|{\mathbb{P}(V = k) − \mathbb{P}(W = k)}| \leq 2p}
2
. (40)
La cota (39) se deduce de observar que
|{\mathbb{P}(V = k) − \mathbb{P}(W = k)}| = |{E[1 \{V = k}\] − E[1 \{W = k}\]|
= |{E[1\{V = k{\} − 1}\W = k{\] | 
\leq E[|{1}\{V = k\} − 1}\{W = k\}|]
\leq E[1 \{V \neq W \]
= \mathbb{P}(V \neq W ).
La cota (40) se deduce de observar que para todo k = 0, 1, \dots}
|{\mathbb{P}(V = k) − \mathbb{P}(W = k)}| = |{\mathbb{P}(V = k, W \neq k) − \mathbb{P}(W = k, V \neq k)|
\leq \mathbb{P}(V = k, V \neq W ) + \mathbb{P}(W = k, V \neq W ), 
y luego sumar sobre los posibles val ores de k:
X
k
|{\mathbb{P}(V = k) − \mathbb{P}(W = k)}| \leq 2\mathbb{P}(V \neq W ).
17
**** Nota Bene 
Esta técnica, denominada técnica de acoplamiento de variables aleatorias,}
permite probar (sin usar la fórmula de Stirling) que la distribución Binomial converge a la
distribución Poisson.
**** Teorema 2.5 (Le Cam). Sean X}
1
, \dots , X
n
variables aleatorias inde pendientes con distribu
ción Bernoulli de parámet ros p
1
, \dots , p
n
, respectivamente y sea S =
P
n
{i=1}
X
i
. Entonces
X
k
|{\mathbb{P}(S = k) − \mathbb{P}(N = k)}| \leq 2}
n
X
{i=1}
p
2
i
, (41)
donde N es una variable aleatoria con distribución Poisson de media \lambda =
P
n
{i=1}
p
i
.
**** Demostración 
Sean U
1
, \dots , U
n
variables aleatorias independientes con distribución común
U[0, 1). Construimos variables aleatorias acopladas V
i
\sim Bernoulli(p}
i
) y W}
i
\sim{Poisson(p}
i
),
i = 1, \dots , n{:}
V
i
:= 1\{U 
i
\in I}
1
(p
i
)\, W
i
:=
\infty
X
{k=0}
k{1{\}U
i
\in J}
k
(p
i
)\, 
y las sumamos
S
∗
=
n
X
{i=1}
V
i
, N =}
n
X
{i=1}
W
i
.
Por construcción, las variables V}
1
, \dots , V
n
son independientes y con distribución Bernoulli(p
i
),
respectivamente, y entonces, la variable S}
∗
tiene la misma distribución que S}; las variables
W
1
, \dots , W
n
son independientes y tienen distribución Poisson(p
i
), respectivamente, y entonces,
la variable N tiene distribución Poisson de media \lambda =
P
n
{i=1}
p
i
.
Observando que cada k
|{\mathbb{P}(S 
∗
= k) − \mathbb{P}(N = k)| \leq \mathbb{P}(S}
∗
= k, N \neq k) + \mathbb{P}(N = k, S}
∗
\neq k).
se obtiene que
X
k
|{\mathbb{P}(S 
∗
= k) − \mathbb{P}(N = k)| \leq 2\mathbb{P}(S}
∗
\neq N).
Si S}
∗
\neq N, entonces V
i
\neq W
i
para algún i = 1, \dots , n}. En consecuencia,
\mathbb{P}(S
∗
\neq N) \leq
n
X
{i=1}
\mathbb{P}(V
i
\neq W
i
) \leq}
n
X
{i=1}
p
2
i
.
**** Corolario 2.6 (Aproximación Poisson). Para cada k \geq 0  
\lim_{n  \rightarrow \infty}

n
k

1 −}
\lambda
n

n{−}k

\lambda
n

k
= e
− \lambda 
\lambda
k
k{!}
18
**** Demostración 
Sean U
1
, \dots , U
n
variables aleatorias independientes con distribución común
U[0, 1). Para cada i = 1, \dots , n definimos parejas de variables aleatorias (V
i
, W
i
) independientes
V
i
:= 1\{U 
i
\in I}
1
(p)\, W
i
:=
\infty
X
{k=0}
k{1{\}U
i
\in J}
k
(p)\}.
Por construcción, V}
i
\sim Bernoulli(p) y W
i
\sim Poisson(p), en consecuencia las sumas}
S =}
n
X
{i=1}
V
i
, N =}
n
X
{i=1}
W
i
son variables aleatorias con distribuciones Binomial(n, p) y Poisson(np), respectivamente. De
acuerdo con la demostración del Teorema de Le Cam tenemos que






n
k

1 −}
\lambda
n

n{−}k

\lambda
n

k
− e
− \lambda 
\lambda
k
k{!}





= |\mathbb{P}(S = k) − \mathbb{P}(N = k)| \leq 2{np}
2
= 2
\lambda
2
n
\rightarrow 0.
**** Teorema 2.7. Supongamos que para cada n, X}
n,{1}
, \dots , X
n,r
n
son variables aleatorias inde
pendientes con distribución Bernoulli(p}
n,k
). Si}
r
n
X
{k=1}
p
n,k
\rightarrow \lambda \geq 0, máx}
1{\leqk\leqr}
n
p
n,k
\rightarrow 0, (42)
entonces
P
r
n
X
{k=1}
X
n,k
= i
!
\rightarrow e
− \lambda 
\lambda
i
i{!}
, i = 0, 1, 2, \dots . (43)
Si \lambda = 0}, el límite (43) se interpreta como 1 para i = 0 y 0 para i \geq 1 . En el caso r
n
= n
y p
n,k
= \lambda/n, (43) es la aproximación Poisson a la binomial. Notar que si \lambda > 0}, entonces
(42) implica que r
n
\rightarrow \infty.
**** Demostración 
Sea U
1
, U
2
, \dots una sucesión de variables aleatorias independientes, con}
distribución común U[0, 1). Definimos
V
n,k
:= 1\{U 
k
\in I}
1
(p
n,k
)\}.
Las variables V}
n,{1}
, \dots , V
n,r
n
son independientes y con distribución Bernoulli(p
n,k
). Puesto que
V
n,{1}
, \dots , V
n,r
n
tienen la misma distribución que X
n,{1}
, \dots , X
n,r
n
, (43) se obtiene mostrando
que V}
n
=
P
r
n
{k=1}
V
n,k
satisface
\mathbb{P}(V
n
= i) \rightarrow e}
− \lambda 
\lambda
i
i{!}
. (44)
Ahora definimos
W
n,k
:=
\infty
X
{i=0}
i{1{\}U
k
\in J}
i
(p
n,k
)\}
19
W
n,k
tiene distribución Poisson de media p
n,k
. Puesto que las W}
n,k
son independientes, W}
n
=
P
r
n
{k=1}
W
n.k
tiene distribución Poisson de media \lambda}
n
=
P
r
n
{k=1}
p
n,k
. De la desigualdad 1{−p \leq e}
−p
,
se obtiene como consecuencia que
\mathbb{P}(V
n,k
\neq W
n,k
) = \mathbb{P}(V}
n.k
= 1 \neq W}
n,k
) = \mathbb{P}(U}
k
\in I}
1
(p
n,k
) − J
1
(p
n,k
))
= p
n,k
− e
−p
n,k
p
n,k
\leq p
2
n,k
,
y por (42)
\mathbb{P}(V
n
\neq W
n
) \leq}
r
n
X
{k=1}
p
2
n,k
\leq \lambda}
n
máx
1{\leqk\leqr}
n
p
n,k
\rightarrow 0.
(44) y (43) se obtienen de observar que
\mathbb{P}(W
n
= i) = e
− \lambda 
n
\lambda
i
n
n{!}
\rightarrow e
− \lambda 
\lambda
n
n{!}
.
* Cuentas con exponenciales
** Motivación: pasaje de lo discreto a lo continuo
Para fijar ideas consideraremos una conversación telefónica y supondremos que su duración
es un número entero de segundos. La duración de la conversación será tratada como una
variable aleatoria T cuya distribución de probabilidades p
n
= \mathbb{P}(T = n) es conocida. La línea
telefónica representa un sistema físico con dos estados posibles /"ocupada"/(E}
0
) y /"libre"/(E}
1
).
Imaginemos que cada segundo se decide si la conversación continúa o no por medio de
una moneda cargada. En otras palabras, se realiza una sucesión de ensayos Bernoulli con
probabilidad de éxito p a una tasa de un ensayo por segundo y se continúa hasta el primer
éx ito. La conversación termina cuando ocurre el primer éxito. En este caso la duración total
de la conversación, el tiempo de espera, tiene distribución geométrica p
n
= (1 − p)
n{−{1
p. Si en}
un instante cualquiera la línea está ocupada, la probabilidad que permanezca ocupada por
más de un segundo es (1 − p), y la probabilidad de transición E}
0
\rightarrow E}
1
en el siguiente paso
es p. En este caso esas probabilidades son independientes de cuánto tiemp o estuvo ocupada
la línea.
La descripción de los tiempos de espera mediante modelos discretos presupone la cuanti
zación del tiempo y que l os cambios solo pueden ocurrir en las épocas ε, 2{ε, \dots . El tiempo de
espera T más sencillo es el tiempo de espera hasta el primer éxito en una sucesión de ensayos
Bernoulli con probabilidad de éxito p(ε). En tal caso \mathbb{P}(T > nε) = (1 − p(ε))
n
y el tiempo
medio de espera es E[T ] = ε/p(ε). Este modelo puede se puede refinar haciendo que ε sea
cada vez más chico pero manteniendo fija la esperanza ε/p(ε) = 1{/\lambda}. Para un intervalo de
duración t corresponden aproximadamente n \approx t/ε ensayos, y entonces para ε pequeño
\mathbb{P}(T > t) \approx (1 − \lambdaε})
t/ε
\approx e
−{\lambda t}
. (45)
Este modelo considera el tiempo de esp era como una variable aleatoria discreta distribuida
geométricamente y (45) dice que /"en el límite"/ se obtiene una distribución exponencial.
20
Si no discretizamos el tiempo tenemos que tratar con variables aleatorias continuas. El rol
de la distribución geométrica para los tiempos de espera lo ocupa la distribución exponencial.
Es la única variable continua dotada de una completa falta de memoria. En otras palabras, la
probabilidad de que una conversación que llegó hasta el tiempo t continúe más allá del tiempo
t + s es independiente de la duración pasada de la conversación si, y solo si, la probabilidad}
que la conversación dure por lo menos t unidades de tiempo está dada por una exponencial
e
−{\lambda t}
.
**** Nota Bene Si en un momento arbitrario t la línea está ocupada, entonces la probabilidad}
de un cambio de estado durante el próximo segundo depende de cuan larga ha sido la con
versación. En otras palabras, el pasado inﬂuye sobre el futuro. Esta circunstancia es la fuente
de muchas dificultades en problemas más complicados.
** Distribución exponencial
Se dice que la variable aleatoria T tiene distribución exponencial de intensidad \lambda > 0 y se 
denota T \sim Exp( \lambda ) si la función de distribución de T es de la forma
F
T
(t) := \mathbb{P}(T \leq t) =

1 − e}
−{\lambda t}

1\{t \geq 0}\. (46) 
En tal caso T admite la siguiente función densidad de probabilidades
f
T
(t) = \lambda e}
−{\lambda t}
1\{t \geq 0}\. (47) 
Media y Varianza. Los valores de la esperanza y la varianza de T son, respectivamente,}
E[T ] = 1{/\lambda y V(T ) = 1{/\lambda
2
.
** Suma de exponenciales independientes de igual intensidad
**** Teorema 3.1. Sean T_1
, T_2
, \dots , T_n
variables aleatorias independientes, idénticamente dis
tribuidas, con distribución exponencial de intensidad \lambda > 0. La suma S_n
= T}
1
+  \cdots  + T_n
admite una densidad de probabilidades de la forma
f
S_n
(t) = \lambda e}
−{\lambda t}
(\lambda t)
n{−{1
(n − 1)!
1\{t > 0}\} (48)}
y su función de distribución es
F
S_n
(t) =
1 − e}
−{\lambda t}
n{−{1
X
{i=0}
(\lambda t)
i
i{!}
!
1\{t \geq 0}\. (49) 
En otras palabras, la suma de n variables aleatorias independientes exponenciales de intensi
dad \lambda > 0 tiene distribución Gamma de parámetros n y \lambda}: \Gamma(n, \lambda).
21
**** Demostración 
Por inducción. Para n = 1 no hay nada que probar: S
1
= T}
1
\sim Exp( \lambda ).
Supongamos ahora que la suma S_n
= T}
1
+  \cdots  + T_n
admite una densidad de la forma (48).
Debido a que las variables aleatorias S_n
y T}
{n+1}
son independientes, la densidad de S}
{n+1}
=
S_n
+ T}
{n+1}
se obtiene convolucionando las densidades de S_n
y T}
{n+1}
:
f
S
{n+1}
(t) = (f
S_n
∗ f
T
{n+1}
)(t) =
Z
t_0
f
S_n
(t − x)f
T
{n+1}
(x)dx}
=
Z
t_0
\lambda e
−{\lambda ( t}−{x ) 
( \lambda (t − x))
n{−{1
(n − 1)!
\lambda e
−{\lambda x}
dx
= \lambda e}
−{\lambda t}
\lambda
n
(n − 1)!
Z
t_0
(t − x)
n{−{1
dx = \lambda e
−{\lambda t}
\lambda
n
(n − 1)!
t_n
n
= \lambda e}
−{\lambda t}
(\lambda t)
n
n{!}
.
Las funciones de distribución (49) se obtienen integrando las densidades (48). Sea t \geq 0,
integrando por partes puede verse que
F
S_n
(t) =
Z
t_0
f
S_n
(s)ds =
Z
t_0
(\lambda s)
n{−{1
(n − 1)!
\lambda e
−{\lambda s}
ds
= −}
(\lambda s)
n{−{1
(n − 1)!
e
−{\lambda s}




t_0
+
Z
t_0
(\lambda s)
n{−{2
(n − 2)!
\lambda e
−{\lambda t}
ds
= −}
(\lambda t)
n{−{1
(n − 1)!
e
−{\lambda t}
+ F}
S_n{−{1
(t). (50)
Iterando (50) obtenemos (49).
**** Nota Bene 
En la demostración anterior se utilizó el siguiente resultado: si T_1
, \dots , T_n
son
variables aleatorias indepe ndientes, entonces funciones (medibles) de familias disjuntas de las
T
i
también son independientes. (Para más detalles ver el Capítulo 1 de Durrett, R., (1996).
Probability Theory and Examples, Duxbury Press, New York.)
** Mínimos
**** Lema 3.2. Sean T_1
y T}
2
dos variables aleatorias independientes y exponenciales de intensi
dades \lambda}
1
y \lambda}
2
, respectivamente. Vale que
\mathbb{P}(T_1
< T_2
) =
\lambda
1
\lambda
1
+ \lambda}
2
. (51)
**** Demostración 
La probabilidad \mathbb{P}(T_1
< T_2
) puede calcularse condicionando sobre T}
1
:
\mathbb{P}(T_1
< T_2
) =
Z
\infty
0
\mathbb{P}(T_1
< T_2
|{T}
1
= t)f
T_1
(t)dt =
Z
\infty
0
\mathbb{P}(t < T_2
) \lambda 
1
e
− \lambda 
1
t
dt
= \lambda}
1
Z
\infty
0
e
− \lambda 
2
t
e
− \lambda 
1
t
dt = \lambda
1
Z
\infty
0
e
−( \lambda }
1
+ \lambda 
2
)t
dt =}
\lambda
1
\lambda
1
+ \lambda}
2
.
22
**** Teorema 3.3. Sean T_1
, T_2
, \dots , T_n
variables aleatorias exponenciales independientes de in
tensidades \lambda}
1
, \lambda
2
, \dots , \lambda
n
, respectivamente. Sean T y J las variables aleatorias definidas por
T := mín}
i
T
i
, J := índice que realiza T.}
Entonces, T tiene distribución exponencial de intensidad \lambda}
1
+  \cdots  + \lambda}
n
y
\mathbb{P}(J = j) =}
\lambda
j
\lambda
1
+  \cdots  + \lambda}
n
.
Más aún, las variables T y J son independientes.
**** Demostración 
En prime r lugar, hay que observar que T > t si y solo si T
i
> t para}
todo i = 1, \dots , n}. Como las variables T}
1
, T_2
, \dots , T_n
son exponenciales independientes de
intensidades \lambda}
1
, \lambda
2
, \dots \lambda
n
tenemos que
\mathbb{P}(T > t) =}
n
Y
{i=1}
\mathbb{P}(T
i
> t) =}
n
Y
{i=1}
e
− \lambda 
i
t
= e
−( \lambda }
1
+{\cdots}+ \lambda 
n
)t
.
Por lo tanto, T tiene distribución exponencial de intensidad \lambda}
1
+  \cdots  + \lambda}
n
.
En segundo lugar hay que observar que J = j si y solo si T = T}
j
. Por lo tanto,
\mathbb{P}(J = j) = \mathbb{P}(T
j
= mín
i
T
i
) = \mathbb{P}(T}
j
< mín}
i{\neq} j
T
i
) =
\lambda
j
\lambda
1
+  \cdots  + \lambda}
n
.
La última igualdad se obtiene utilizando el Lema 3.2 pues las variables T}
j
y mín
i{\neq} j
T
i
son
independientes y exponenciales con intensidades \lambda}
j
y
P
i{\neq} j
\lambda
i
, respectivamente.
Finalmente, si para cada j definimos U}
j
= mín
i{\neq} j
T
i
, tenemos que
\mathbb{P}(J = j, T \geq t) = \mathbb{P}(t \leq T
j
< U
j
)
=
Z
\infty
t
\mathbb{P}(T
j
< U
j
|{T}
j
= s) \lambda 
j
e
− \lambda 
j
s
ds
= \lambda}
j
Z
\infty
t
\mathbb{P}(U
j
> s ) e
− \lambda 
j
s
ds = \lambda
j
Z
\infty
t
e
− ( 
P
i{\neq} j
\lambda
i
)s
e
− \lambda 
j
s
ds
=
\lambda
j
\lambda
1
+  \cdots  + \lambda}
n
Z
\infty
t
( \lambda 
1
+  \cdots  + \lambda}
n
)e
−( \lambda }
1
+{\cdots}+ \lambda 
n
)s
ds
=
\lambda
j
\lambda
1
+  \cdots  + \lambda}
n
e
−( \lambda }
1
+{\cdots}+ \lambda 
n
)t
.
Lo que completa la demostración.
**** Ejercicios adicionales
4. Sean T_1
y T}
2
variables aleatorias independientes exponenciales de intensidad 2. Sean
T
(1)
= mín(T}
1
, T_2
) y T}
(2)
= máx(T}
1
, T_2
). Hallar la esperanza y la varianza de T}
(1)
y de T}
(2)
.
23
5. Suma geométrica de exponenciales independientes. Sean T 
1
, T_2
, \dots variables aleatorias}
independientes idénticamente distribuidas con ley exponencial de intensidad \lambda}. Se define
T =}
P
N
{i=1}
T
i
, donde N es una variable aleatoria con distribución geométrica de parámetro
p, independiente de las variables T_1
, T_2
, \dots . Hallar la distribución de T . (Sugerencia{: Utilizar 
la fórmula de probabilidad total condicionando a los posibles valores de N y el desarrollo en
serie de Taylor de la función exponencial.)
* Bibliografía consultada
Para redactar estas notas se consultaron los siguientes libros:
1. Billingsley, P.: Probability and measure. John Wiley & Sons, New
   York. (1986)
2. Durrett R.:Probability. Theory and Examples. Duxbury Press,
   Belmont. (1996)
3. Feller, W.: An introduction to Probability Theory and Its
   Applications. Vol. 1. John Wiley & Sons, New York. (1957)
4. Feller, W.: An introduction to Probability Theory and Its
   Applications. Vol. 2. John Wiley & Sons, New York. (1971)
5. Grimmett, G. R., Stirzaker, D. R.: Probability and Random
   Processes. Oxford University Press, New York. (2001)
6. Meester, R.: A Natural Introduction to Probability Theory. Birk
   hauser, Berlin. (2008).
7. Meyer, P. L.: Introductory Probability and Statistical
   Applications. Addison-Wesley, Massachusetts. (1972)
8. Ross, S. M: Introduction to Probability and Statistics for
   Engineers and Scientists. Elsevier Academic Press, San
   Diego. (2004)
9. Soong, T. T.: Fundamentals of Probability and Statistics for
   Engineers. John Wiley & Sons Ltd. (2004)
 
 
 
 
 
 
 
 


