#+title: Costos
* Concepto
** Concepto Tradicional
- Para valorizar Inventarios
- Para fijar precios de venta

#+BEGIN_EXAMPLE
Costos + Utilidad = Precio de Venta
#+END_EXAMPLE

** Concepto Moderno
- Tomar decisiones
- Medir Eficiencia

#+BEGIN_EXAMPLE
Precio de Venta - Costos = Utilidad?
#+END_EXAMPLE

** Objetivo principal
- Conocer cuánto me cuesta producir y vender un producto o servicio.
- Tener un mejor escenario para definir el futuro de la Empresa.

Costo unitario = $\frac{\$gastos}{volumen\ de\ actividad}$

Eficiencia productiva = $\frac{cuanto\ se\ obtiene}{cuanto\ se\ consume}$

Si se quiere bajar costos se debe aumentar la eficiencia.

* Contabilidad de Costos
Rama de la contabilidad administrativa que sintetiza y registra los
desembolsos de los sectores fabril – de servicios y comercial.

- Provee información contable para poder hacer un cálculo razonable de
  costos.
- Registra op. Internas y las transacciones con 3os

#+BEGIN_EXAMPLE
Con que frecuencia?
├ Análisis de Balance se realiza anualmente
└ Análisis de Costos mensual, bimestral. 
#+END_EXAMPLE

Se tendrán costos razonables si tenemos una información confiable
brindada por la Contabilidad de costos.

- Contabilidad: es el proceso de identificar, medir, registrar y
  comunicar los eventos económicos de una organización (con o sin fin
  de lucro), para usuarios interesados en dicha información.
- Objeto: brindar información
- Objetivo: medición del patrimonio y determinación del resultado.
- Contabilidad administrativa: proporciona información a nivel interno.
- Usuarios de la CA: gerente comercial, gerente de producción,
  presidente de la empresa, ingenieros, etc. Sirve para tomar
  decisiones no rutinarias.
- Contabilidad financiera: proporcioa informacion a nivel externo ->
  Balance General, Estado de Resultados, Estado de Origen y Aplicacion
  de Fondos. PCGA - CPCE.
- Usuarios de la CF: accionistas, banqueros, proveedores, clientes,
  competencia, entes gubernamentales, etc.
- Contabilidad de costos: corresponde a una aplicación específica de
  la contabilidad administrativa que está relacionada con los
  procedimientos diseñados para determinar el costo de un producto.

|                     | Contabilidad Administrativa                                    | Contabilidad Financiera                                                             |
|                     | Proporciona info. a nivel interno                              | Proporciona info. a nivel externo                                                   |
| Usuarios            | Gerentes de la organización a varios niveles                   | Accionistas, bancos, proveedores, clientes,competencia, entes gubernamentales, etc. |
| Restricciones       | Ninguna a excepción de los costos en relación a los beneficios | PCGA - CPCE                                                                         |
| Enfoque temporal    | Hacia el futuro                                                | Hacia el pasado                                                                     |
| Intervalo de tiempo | Flexible, desde horas hasta años                               | Menos flexible. Por lo general un año o un trimestre                                |
| Reportes            | Detallados                                                     | Resumidos                                                                           |

* Que contabilidad de costos necesitamos?
- La que nos brinde un valor de inventarios con la rapidez y el
  desglose requerido.
- La que tenga un Plan de Cuentas lo más amplio posible que nos
  indique cuánto, en qué y donde se gastó.
- La que brinde una adecuada DEPARTAMENTALIZACIÓN en centros de costos
  productivos y de servicios.

* Clasificacion de costos
#+BEGIN_EXAMPLE
Segun sistema de acumulacion de costos
├ Costeo por Orden de Trabajo
└ Costeo por Proceso
 
Segun el momento de su determinacion
├ Historico
├ Historico con cuota
└ Estandar 

Segun el tratamiento de los Gastos Fijos
├ Costeo por Absorcion
└ Costeo Directo
#+END_EXAMPLE

Ejemplo: 
#+BEGIN_EXAMPLE
Costeo por Ordenes - Historico y por Absorcion

Costeo por Procesos - Estandar y Directo
#+END_EXAMPLE

** Segun Sistema de Acumulacion de Costos
*** Costeo por Ordenes de Trabajo
- Cada pedido se trata como un output especial. Los costos se imputan
  a los pedidos.
- Los costos se acumulan por trabajos.
- Amplia variedad de productos o servicios.
- Costo unitario = Costo total de la orden / unidades integrantes de
  la orden.
- El costo por órdenes de fabricación acumula y asigna los costos para
  cada pedido.
- Bajo un sistema de costos por órdenes de fabricación, los costos son
  asignados a cada trabajo o pedido.
- Una característica importante de los sistemas de costos por órdenes
  de pedido es que cada trabajo (o pedido) tiene una serie de
  características distintivas propias.
- El proceso productivo es por pedido 
- El objetivo de los sistemas de costos por órdenes de fabricación es
  el cálculo del costo por pedido, más que por un periodo de tiempo.
- Ejemplos de actividades donde se emplea Órdenes de Fabricación:
  - Imprentas
  - Astilleros
  - Fabricantes de muebles
  - Constructores
  - Compañías cinematográficas
  - Asesorías y gestorías
  - Agencias de publicidad
  - Clínicas médicas

*** Costeo por Procesos
- Cada unidad procesada es tratada como output unitario. Los costos se
  imputan a cada unidad.
- Los costos se acumulan por procesos o departamentos.
- Producción masiva de productos o servicios homogéneos.
- Costo unitario = Costos totales del periodo / unidades producidas o
  servidas.
- Acumula los costos de cada producto o servicio para cada
  departamento de la empresa, y posteriormente lleva a cabo la
  asignación de los mismos entre un conjunto de unidades idénticas de
  producto/servicio.
- Un sistema de costos por procesos o departamentos se emplea cuando
  un conjunto de procesos de fabricación producen
- El proceso productivo es continuo.
- Los costos se acumulan para un periodo determinado de tiempo, al
  contrario que en el caso de pedidos u órdenes de fabricación.
- Ejemplos de actividades donde se emplea Procesos o Departamentos
  - Plantas químicas
  - Procesadores de alimentos
  - Fabricantes de componentes
  - Empresas textiles
  - Fabricantes de derivados del petróleo
  - Papeleras
  - Aserrerías
  - Vidrieras

** Segun el Momento de su Determinacion
*** Sistema de Costeo Estandard
Sistema de costeo predeterminado a estándar de valuación de
inventarios.
- Por Absorción (considero los GGF Fijos y Variables)
- Directo (considero sólo los costos proporcionales)

imagen

Para su ejecucion es necesario
- Plan de cuentas y mayor grado de analisis en la contabilidad.
- Departamentalización con asignacion de responsabilidades.

*** Objetivo del Costo Estandar
Calcular anticipadamente cual debería ser el costo de un producto
utilizando la máxima eficiencia posible con la tecnología disponible.

#+BEGIN_EXAMPLE
ES EL MEJOR COSTO PRESUPUESTADO POSIBLE
#+END_EXAMPLE

Pasos a seguir:
- Definir el nivel de actividad (NA)
- Determinar la MP que genere menores mermas y de calidad
- Mano de Obra Directa. La necesaria para obtener los mejores costos
  operativos
- Nivel de Gastos Generales de Fabricación para lograr los objetivos

Al ser un costeo predeterminado, de su comparación con lo real surgen
las variaciones.

El costo estándar nos da la mayor información para analizar las
ineficiencias y ver dónde podemos trabajar para disminuir las
variaciones de precio y cantidad y las variaciones los Gastos
Generales de Fabricación

Las variaciones de cantidad deberían ser manejables por la empresa

Las variaciones de precio son menos manejables que las variaciones de
cantidad

* Elementos del Costo
- Materia Prima (MP): elementos físicos que la empresa consume y se
  transforman en otro producto.
  #+BEGIN_EXAMPLE
  Si fabrico latón la MP es Cu y Zn
  Si fabrico papel la MP es la pasta de celulosa.
  #+END_EXAMPLE
- Mano de Obra Directa (MOD): representa el valor del trabajo del
  personal necesario para transformar la MP y realizar el producto
  final. Existen gastos conexos, como las CCSS.
- Gastos Generales de Fabricación (GGF): son todas las erogaciones que
  necesita afrontar la empresa para realizar la producción: gastos de
  energía, seguros, amortizaciones, impuestos, que no pueden imputarse
  en forma directa.
- Costos de Distribución: costo comercial, comisiones de vendedores,
  gastos de logística.

#+BEGIN_EXAMPLE
Debemos asignar estos elementos del costo a los productos terminados
#+END_EXAMPLE

imagen gastos generales

Definido el nivel de actividad de cada centro productivo, calcular la
cuota de aplicacion de gastos indirectos.

** Costeo por Absorcion
\beta(c) = \frac{$ gastos\ indirectos\ del\ CP}{Nivel\ de\ Actividad\ CP}

** Costeo Variable / Directo
\alpha(c) = \frac{$ gastos\ variables\ o\ directos}{Nivel\ de\ Actividad\ del\ CP}

Si el calculo de costos es incorrecto en cuanto a la asignacion de
GGF, obtendremos costos unitarios incorrectos e inducira a toma de
decisione erroneas.

C_{unit ABS} = MP + MOD + \beta(c) * Std.fisico

C_{unit DIR} = MP + MOD + \alpha(c) * Std.fisico

Costeo Directo vs Costeo por Absorcion
| Costeo Directo / Variable                                                                                  | Costeo por Absorcion                                                                         |
| Método de costeo de inventarios. Todos los costos variables de fabricación se incluyen como inventariables | Método de costeo de inventarios. Todos los costos de producción se consideran inventariables |
| Los costos variables de producción se consideran costos del producto                                       | Todos los costos de producción son costos del período                                        |
| Los costos fijos de producción se consideran costos del período                                            | El inventario absorbe todos los costos                                                       |
| Los estados financieros elaborados son para fines internos (para la gerencia)                              | Los estados financieros bajo este método son para uso externo                                |
| La utilidad es función de las ventas                                                                       | La utilidad es función de las ventas y del nivel  de actividad $U = f(p_V,NA)$               |

imagen costeo por absorcion vs costeo directo

* Variaciones
** Variaciones de MP
imagen calculo de variaciones de MP

*** Variación de precio de MP
\Delta P_{MP} = Q_{Real comprada} ( P_{Real} − P_{Std} )

*** Variación de cantidad de MP
\Delta Q_{MP} = P_{Std} ( Q_{Real} − Q_{Std} )

\Delta Q_{MP} = P_{Std} Q_{Real} − P_{Std} Q_{Std}

Q_{Real} : salida de almacen x kilos

Q_{Std} : cantidad requerida para hacer 1 unidad std

Q_{Std} : produccion real a precio std (Prod_{Real}u * Precio_{std}Kg/u)

\Delta Q_{MP} = Vales de retiro de almacén − Q de MP a efic. Std para producir la Act. Real

** Variaciones de MOD
imagen 

\Delta PyQ_{MOD} = P_{Real} Q_{Real} - P_{Std} Q_{Std}

*** Variación de precio de MOD
\Delta P_{MOD} = Q_{Real} hh  ( P_{Real} − P_{Std} )

*** Variación de cantidad de MOD

\Delta Q_{MOD} = P_{Std} ( Q_{Real} − Q_{Std} )  

\Delta Q_{MOD} = P_{Std} Q_{Real} − P_{Std} Q_{Std}

Q_{Std} = horas Std para fabricar la cantidad real de unidades

** Variacion de Presupuesto
\Delta Presupuesto = Gasto Real - Gasto Presupuestado

\Delta Presupuesto_{CP} = GGF Real - ( GG Fijo_{Prop} + \alpha_{CP} * NACT_{Real valorizado a Std} )

\Delta Presupuesto_{CS} = GGF Real - ( GG Fijo_{Prop} + \alpha_{CS} * NACT_{CS Real valorizado a Std} )

\alpha_{CS} : GGF Std / NACT_{CS Std} (de los CP que suministra)

NACT_{CS Real valorizado a Std} : \sum_{i \in CP que suministra} NACT_{Real valorizado a Std del CPi}

 imagen

** Variacion de Volumen

\Delta Volumen = \sum GGF Presupuestado - GGF Aplicado

\Delta Volumen = \sum_{i} GGF Presupuestado_{Centro i} - ( \beta * NACT_{Real} )

 imagen

Se calcula en los centros productivos exclusivamente - o para la
empresa en su conjunto - y se trabaja con el presupuesto flexible
total, gastos propios más prorrateados.

 imagen

 imagen
* Costeo ABC (Activity-Based Costing)
** Por Qué Se Quiere Mejorar El Calculo De Costos ?
Es claro el hecho, que el cálculo exacto de los costos unitarios de
los productos y servicios, facilita la estrategia comercial y
competitiva de la empresa, ya que de la confrontación de los precios
de mercado, con los costos de los productos, es posible determinar el
real nivel de competitividad que tiene la empresa; que productos
debieran potenciar, que productos debieran dejar de producir, etc

** Asignando Gastos Generales A Productos
*** Tasa (o cuota) única para toda la empresa

Es un método simple pero que distorsiona los costos por unidad de
producto

Frecuentemente las horas de mano de obra directa se usaron como base
para asignar los gastos generales

Hoy, es muy raro que las horas hombre de mano de obra directa sean una
base satisfactoria para asignar gastos.
- No están correlacionadas de manera importante.
- Una base única no puede reflejar las diferentes demandas de GG que
  tienen los distintos productos

*** Tasas (o cuotas) departamentales (una por cada centro de costos)
Las bases de asignación dependen de la naturaleza del trabajo
realizado en cada centro. En MAQUINADO, los GG pueden asignarse sobre
la base de las horas máquina, pero en MONTAJE podrían basarse en las
horas hombre directas

Desafortunadamente, aún las cuotas por centro no logran asignar
correctamente los GG en situaciones donde la empresa tienen un gran
rango de productos y o sus GG son complejos.

Varias bases de distribución se usan para asignar gastos a productos
#+BEGIN_EXAMPLE
Costos -> Consumo De Recursos -> Actividades -> Objetos De Costos (Ej. Productos Para Clientes)
#+END_EXAMPLE

** Pool
POOL de costos de actividad un “balde de costos” en el cuál los costos
de una actividad en particular son acumulados

Cada actividad tiene su propia cuota que se usa para aplicar gastos.

** Pasos para implementar el ABC
1. Identificar y definir activitividades (y sus “pools”) y desarrollar
   un diccionario de actividades.
2. “Tracear”, rastrear, o asignar costos a actividades
3. Calcular cuotas de actividades.
4. Asignar costos a objetos de costos.
5. Informar.

Cuando una empresa implementa ABC, parte de los GGF suelen pasar de
productos de alto volumen a productos de bajo volumen. El costo
unitario de producto de bajo volumen suelen incrementar su costo
unitario, a.c ocurre con prod. de alto volumen.

** Enfocando en mejoras de procesos
*** Activity-Based Management 
ABM incvolucra enfocar en actividades para reducir desperdicio,
disminuir tiempos de proceso, y reducir defectos.

*** Benchmarking
Método sistemático para identificar las actividades con mayor
potencial de mejora. Está basado en comparar la performance en una
empresa con la performance de otra, (empresas similares, conocidas por
su performance sobresaliente)

** Evaluacion del ABC
| Beneficios                                                                             | Limitaciones                                                                                         |
|----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------|
| Mejora la exactitud de los costos                                                      | Los costos de implementación puede exceder los beneficios                                            |
| Las pools de costos de actividad son más homogéneas que las pools de centros de costos | En algunos casos (especiales, pero posibles al fin) no es imprescindible la exactitud de los costos. |
| Asigna GGF sobre la base de las actividades que los causan                             |                                                                                                      |

** Cuando Es Más Razonable Aplicar El Costeo ABC
- Los costos indirectos de fabricación tienen una alta significación
  relativa en el costo total de los productos.
- La medida de volumen usada por el costeo tradicional para distribuir
  los costos indirectos de fabricación, no guarda una adecuada
  relación con la demanda por costos indirectos de fabricación que
  realizan los distintos productos.
- Existencia de variados productos, con distintos grados de
  complejidad entre ellos, ya sea en actividades asociadas al proceso
  productivo o en actividades de soporte a la producción.
- Existencia de actividades y causantes del costo, claramente
  identificables y fácilmente medibles, que permitan distribuir
  correctamente los costos indirectos de fabricación a los distintos
  productos.

Se debe destacar, que la relación de los costos y sus responsables
(causalidad), bajo el enfoque de costeo ABC, es más clara que el
enfoque tradicional, debido a que los costos bajo el sistema ABC se
consideran variables con respecto a las actividades que los
generan. Es importante señalar que el modelo ABC considera el análisis
de los costos en un período de tiempo que permita visualizar su
comportamiento, el cual no siempre corresponde al período mensual.

** El Costeo ABC Favorece Al Control De Gestion
Desde el punto de vista del control de gestión, el sistema ABC, por
medio de la identificación y valorización de las actividades
realizadas en el área evaluada, permite una reducción racional del
costo de los productos o servicios que entregan las áreas evaluadas
Esto dado que el modelo pone el énfasis en el reconocimiento y
discriminación entre las actividades, causantes de los costos, que
agregan valor al producto y aquellas que no lo agregan y que conforman
los variados procesos y productos que entregan las áreas de la
organización. La eliminación de las actividades no agregativas de
valor bajo el punto de vista del cliente y la mejor manera de realizar
las actividades, que a pesar de no ser agregativas de valor no se
pueden eliminar, lleva a una mejoría en los procesos y a una reducción
en los costos.

** Cuando No Parece Convenir Aplicar Costeo ABC
Se debe tener bastante claro, que el enfoque de costeo ABC se
justifica, cuando el monto de los costos indirectos de fabricación es
significativo respecto de los costos directos. Si ocurre lo contrario,
es decir, sí el costo de la mano de obra directa y/o el de materia
prima, son altamente significativos, en comparación con los costos
indirectos de fabricación y el comportamiento de estos últimos guardan
relación con una o varias medidas de volumen, cabe preguntarse ¿ se
justifica aplicar el sistema de costeo ABC?. La respuesta a esta
interrogante es “no se justifica”, por lo menos para el propósito del
cálculo de los costos unitarios.
 
 
 
 
 
 
