#+title:Finanzas
# +html_head: <Link rel="stylesheet" type="text/css" href="/home/mk/or g.css"/>

#+BEGIN_QUOTE
“Es una rama de la economía que trata el tema relacionado con la obtención y
gestión del dinero, recursos o capital por parte de una persona o empresa.”
#+END_QUOTE

#+BEGIN_QUOTE
“Estudian la manera en que los recursos escasos se asignan a través del tiempo.”
#+END_QUOTE

|           | Informacion Financiera              | Informacion Economica  |
|-----------+-------------------------------------+------------------------|
| Cuenta    | Disponibilidades (Activos Líquidos) | Utilidad del Ejercicio |
|           |                                     | Perdida del Ejercicio  |
|-----------+-------------------------------------+------------------------|
| Tipo      | Activo                              | Patrimonio Neto        |
|-----------+-------------------------------------+------------------------|
| Ubicacion | Libro Diario                        | Libro Diario           |
|           | Libro Mayor                         | Libro Mayor            |
|           | Balance                             | Balance                |
|           |                                     | Cuenta de Resultados   |

* Herramientas Pasado / Presente
  - Dupont
  - Capital de Trabajo
  - Origen y Aplicación de Fondos
  - Comparativa de los Últimos 2 Balances.
  - Índices/Ratios Financieros (Solos o en conjunto con otras
    Herramientas)

  - Diagnosticar Problematicas / Oportunidades
  - Corregir Problematicas Operativas
  - Establecer Metas / Objetivos Estrategicos

* Herramientas a Futuro
  - Presupuesto Integrado:
  - Flujo de fondos Proyectado
  - Balance Proyectado
  - Cuadro de Resultados Proyectado
  - Índices/Ratios Financieros (Solos o en conjunto con otras
    Herramientas)

  - Roadmap Metas / Objetivos Estrategicos
  - Mejorar El Funcionamiento Integrado
  - Evaluar El Progreso De La Metas / Objetivos

* Metas y Objetivos
** Gerencia General
   - Oportunidades y Amenazas del Sector Industrial
   - Contexto Social (Mercado – Gobierno)
   - Establece metas/objetivos ESTRATEGICOS:
     - Aumento de Rentabilidad
     - Aumento de Ventas
     - Disminución de Costos
     - Disminución de Cargas Financieras
   - Motivaciones y Necesidades
   - Fuerzas y Debilidades

** Gerencias/Sub Gerencias
   - Establece Metas/Objetivos Tacticos/Operativos:
     - Necesidad de Personal
     - Necesidad de Activos Fijos
     - Necesidad de Proveedores
     - Necesidad de Bienes de Cambios
     - Necesidad Financiera
   - Relevamiento del Sector
   - Información Económica y Financiera

* Construccion de presupuestos

  | Empresas Nuevas                           | Empresas Existentes                       |
  |-------------------------------------------+-------------------------------------------|
  | Relevamiento con las áreas de la Empresa  | Relevamiento con las áreas de la Empresa  |
  | (Ventas, Compras, Proveedores, Impuestos, | Información Económica y Financiera Pasada |
  | Producción, Personal, Finanzas, Créditos  | (Libro Diario, Libro Mayor, Balance,      |
  | y Cobranzas, Sectores Varios)             | Cuadro de Resultados)                     |

* Deteccion de Baches o Excedentes
  - Presupuesto Financiero/Flujo de Fondos
    - Empresas de pequeña-mediana escala
    - Volumen de dinero pequeño-mediano, y con menos tolerancia a operar
      a descubierto
    - Estimaciones a corto-mediano plazo
    - Mayor complejidad en la construcción de la herramienta para la
      detección del bache o excedente. Proporciona un visión micro

  - Balance: Diferencias de Cuentas
    - Empresas de mediana-gran escala
    - Volumen de dinero mediano-grande, y con mayor tolerancia a operar
      a descubierto
    - Estimaciones a mediano-largo plazo
    - Menor complejidad en la construcción de la herramienta para la
      detección del bache o excedente. Proporciona una visión macro

** Flujo de Fondos
   - El Flujo de Fondo es la proyección/estimación de todos los Ingresos y Egresos
     de Dinero (Cuenta Contable: Caja) en el tiempo.
   - El Flujo de Fondos permite detectar los excedentes y faltantes de dinero (este
     ultimo conocido también como “Bache Financiero”):
     - Permitiendo optimizar la inversión de los excedentes.
     - Permitiendo conocer la necesidad de financiación (prestamos).
     - Permitiendo optimizar otras variables relacionadas para evitar la necesidad
       de financiación (Plazos de cobro, Stocks, etc).

   - Se establece un plazo de tiempo para la proyección / estimación. Normalmente
     de 1 año o 1 ejercicio contable. Se debe subdividir en plazos “adecuados” que
     no escondan los baches o excedentes.
   - Se incluye todos los movimientos que involucran movimiento de dinero (caja),
     durante el plazo definido arriba. Se indica si el mismo corresponde a un
     ingreso (+) o un egreso (-) de dinero.
   - Estos movimiento se ubican en la línea de tiempo según correspondan.
   - Se deben incluir las hipótesis consideradas. Por ejemplo: Hipótesis
     Inflacionarias sobre los Ingresos y Egresos.

** Formula de Flujo de Caja
   - Se conocen los valores proyectados de todas las cuentas del Balance,
     a excepción de la cuenta Caja/Disponibilidades. O en su defecto se
     puede operar con los diferenciales de las cuentas.
   - De la ecuación fundamental de la contabilidad, se despeja la cuenta
     Caja/Disponibilidades del Activo. Se opera matemáticamente a partir
     de la ecuación:

   #+BEGIN_EXAMPLE
   Activo = Pasivo + Patrimonio Neto
   #+END_EXAMPLE

   - Teniendo en consideración como se compone cada grupo de cuentas:
     - Activo = Caja + Créditos + Stock + Activo Fijo
     - Pasivo = Proveedores + Deudas Bancarias
     - Patrimonio Neto = Capital + Utilidades + Reservas
   - Se despeja la cuenta Caja/Disponibilidades:

   #+BEGIN_EXAMPLE
   Caja = Proveedores+ Deudas Bancarias + Capital + Utilidades + Reservas – Créditos – Stock – Activo Fijo
   #+END_EXAMPLE

   #+BEGIN_EXAMPLE
   ΔCaja = ΔProv+ ΔDeudas Bancarias + ΔCapital + ΔUtil + ΔReservas – ΔCréditos – ΔStock – ΔActivo Fijo
   #+END_EXAMPLE

* Movimientos: Ingresos - Egresos
  - Consiste en determinar de los movimientos contables en los que participa la
    Cuenta Disponibilidades/Caja. Se puede tener los movimientos calendarizados
    “Libro Diario” o sumariados “Macro”.
  - De los movimientos contables detectados del punto anterior se busca determinar
    si corresponden a INGRESOS o EGRESOS de Disponibilidades/Caja.
  - Se realiza la diferencia entre la sumatoria de INGRESOS – EGRESOS.

  - Si se tiene los movimientos contables sumariados o macro no se puede construir
    el flujo de fondos

* Excedentes Financieros

  Dias de Caja = $\frac{\text{Cuenta Caja (A)}}{\frac{\sum \text{Gastos Caja Anual
  Año Actual o Anterior*}}{365 Dias }}$


  NO DEBE SUPERAR LOS RAZONABLES PARA ATENDER LA GESTION. TENER EN CUENTA EL MOMENTO DE MAXIMA EXPOSICIÓN (MONTO Y PERIODO DE MAXIMA ERROGACIÓN DE DINERO).
  *El dato se puede obtener de la sumatoria de egresos a la cuenta Caja de la ficha de Libro Mayor


  Dias de Credito Medio = $\frac{\text{Cuenta Crédito (A)}} {\frac{\sum
  \text{Créditos Otorgados Anual Año Actual o Anterior*}}
  {365 Días}}$

  NO DEBE SUPERAR LO QUE REQUIERA PARA MANTENER EL MERCADO DE CLIENTES. TENER EN CUENTA EL TIPO DE EMPRESA, YA QUE VA A DEPENDER EN GRAN MEDIDA DEL PRODUCTO QUE SE VENDA.
  *El dato se puede obtener de la sumatoria de ingresos a la cuenta Créditos de la ficha de Libro Mayor


  Dias de Proveedores = $\frac{\text{Cuenta Proveedores (P)}} { \frac{\sum
  \text{Deuda Proveedores Anual Año Actual o Anterior*}} {365 Días} }$

  NO DEBEN SER MENOS DE LOS QUE REQUIERA EL MERCADO. TENER EN CUENTA EL TIPO DE EMPRESA, YA QUE VA A DEPENDER EN GRAN MEDIDA DE LOS INSUMOS QUE SE REQUIERA.
  *El dato se puede obtener de la sumatoria de ingresos a la cuenta Créditos de la ficha de Libro Mayor


  Dias de Stock = $\frac{\text{Cuenta Stock (A)}} {\frac{\sum \text{C.M.V Primas
  Anual Año Actual o Anterior*}} {365 Días}}$


  NO DEBE SUPERAR EL PLAZO DE “JUST IN TIME”.
  *El dato se puede obtener de la sumatoria de egresos a la cuenta Stock ó C.M.V de la ficha de Libro Mayor


  Días de Producción en Proceso = $\frac{\text{Cuenta Producción en Proceso (A)}}
  { \frac{\sum \text{Retiro de Prod. Proc. Anual Año Actual o Anterior*}} {365
  Días} }$

  DEBERÍA APROXIMAR A LOS COSTO INVOLUCRADOS A UNA PRODUCCIÓN “EFICIENTE”.
  *El dato se puede obtener de la sumatoria de egresos a la cuenta Producción en Proceso de la ficha de Libro Mayor


  Días de Materias Primas = $\frac{\text{Cuenta Materia Prima (A)}} {\frac{\sum
  \text{Retiros de Materias Primas Anual Año Actual o
  Anterior*}} {365 Días}}$

  NO DEBE SUPERAR EL PLAZO DE “JUST IN TIME”.
  *El dato se puede obtener de la sumatoria de egresos a la cuenta Materias Primas de la ficha de Libro Mayor

** Donde aplicar los excedentes?
   - Compra de Mercaderías o Insumos de Producción
     - Se prevé inflación.
     - Se reduce el C.M.V, aumento del margen de ganancias por Ventas.
   - Compra o Modernización de Activos Productivos
     - Cuando produce mejoras productivas y/o ventas
     - Permite un menor costo de producción y/o un mayor precio de ventas
   - Cancelación de Pasivos
     - Cuando produce un ahorro de intereses
   - Compra de Acciones – Bonos – Moneda Extranjera
     - Cuando se prevé aumento de rentabilidad (para la proyección de la Cuenta de
       Resultados se debe prever un valor de venta o re-cotización)
   - Inversión en Plazo Fijo
     - Se produce aumento de la utilidad, por el ingreso secundario de los
       intereses obtenidos
   - Recompra de Acciones de la Empresa
     - Ahorro de dividendos
     - Decisión Estratégica

* Ratios de Liquidez
  - Tipos de Índice de Liquidez:
    - Índice de Liquidez Corriente:

  #+BEGIN_EXAMPLE
      ILC = Activo Corriente / Pasivo
      1.5 <= ILC < 2
  #+END_EXAMPLE

  - Índice de Liquidez “Seco”:
  #+BEGIN_EXAMPLE
      Activo Corriente - Bienes de Cambio / Pasivo Corriente
      ILS ~ 1
  #+END_EXAMPLE

  - Índice de Liquidez Absoluto:
  #+BEGIN_EXAMPLE
      ILA = Disponibilidades / Pasivo Corriente
      ILA ~ 0.3
  #+END_EXAMPLE

* Ratios de Rendimiento
  #+BEGIN_EXAMPLE
  Rendimiento sobre Activos = Utilidad Operativa / Activo
  #+END_EXAMPLE

  #+BEGIN_EXAMPLE
  Rendimiento sobre Patrimonio Neto = Utilidad Despues de IG / Patrimonio Neto
  #+END_EXAMPLE

* Ratios de Endeudamiento
  - Tipos de Índice de Endeudamiento:
    - Índice de Endeudamiento Total:
  #+begin_example
      IET = Pasivo / Activo
      0.4 < IET < 0.6
  #+end_example

  - Índice de Endeudamiento Corriente:
  #+begin_example
      IEC = Pasivo Corriente / Activo
  #+end_example

  - Índice de Solvencia:
  #+begin_example
    IS = Patrimonio Neto / Activo
  #+end_example

* Tecnicas de valuacion de empresas
  #+begin_quote
  "El precio es lo que se paga, el valor es lo que se obtiene” Warren Buffett |
  Inversor y Empresario
  #+end_quote

  #+begin_quote
  “El valor de tu casa es lo que el vecino quiere pagar por ella” -Confucio |
  Pensador
  #+end_quote

  - Factores:
    - Tamaño
    - Tipo de Empresa
    - Pasado y Presente
    - Contexto y Expectativas
    - Cotiza en Bolsa de Valores

  - Valor Contable
  #+begin_example
    Patrimonio Neto = Activo - Pasivo
  #+end_example

  - Valor Contable Ajustado

  #+begin_example
    Activo* - Pasivo*
  #+end_example

  - Activo*: Se eliminan las probables deudores incobrables, se
    eliminan los stocks obsoletos, se recotizan los activos fijos, se
    recotizan las divisas extranjeras, etc.
  - Pasivo*: Se recotizan los pasivos en función de tasas variables,
    etc.

  - Valor de Liquidacion
#+begin_example
    Venta Activo - Cancelacion Pasivo - Gastos Indemnizacion o Despidos
#+end_example

  - Valor de Mercado de las Acciones
#+begin_example
    Valor de Mercado de las Accciones = Cantidad de Acciones * Valor de Mercado de las Acciones
#+end_example

  - Valor de los Dividendos
#+begin_example
    Valor de los Dividendos = Cantidad de Accines * Rentabilidad Obtenida / % Rentabilidad Minima Exigida
#+end_example

  - Multiplo de Ventas
#+begin_example
    Multiplo de Ventas = Ventas Netas * Coeficiente (Industria, Tamaño)
#+end_example

  *Las Ventas Netas se pueden obtener: Cuadro de Resultado, Libro Mayor o Asiento de Cierre

* TODO Origen y Aplicacion de Fondos
  - Refleja las decisiones de inversion y financiacion tomadas por una empresa
    en un periodo de tiempo determinado
  - Puede servir para proyectar la estrategia financiera futura y a partir de su
    analisis con esta metodologia “mejorarla”
  - Algunas sociedades anonimas estan obligadas a presentar estos estados
    contables
  - Para decisiones de adquisiciones y fusiones empresarias. si se dispone de
    suficientes balances de una empresa se puede inferir con razonable precision
    cual fue la estrategia de la empresa en el periodo analizado

  |          | Origen | Aplicacion |
  | Activo   | -      | +          |
  | Pasivo   | +      | -          |
  | Pat Neto | +      | -          |

  - Ordenar por monto los origenes por un lado y las aplicaciones por otro,
    quedarse con los mas significativos en termino de montos de c/u
  - Colocar los aplicaciones de fondos en forma descendente. asignar color para
    las aplicaciones de fondo
  - Colocar los origenes de fondos en forma ascendente. asignar color para los
    origenes de fondo

** Optimizaciones Posibles
   - SEGÚN LOS PRINCIPIOS DE CONFORMIDAD FINANCIERA: EL ACTIVO CORRIENTE (AC) SE
     FINANCIA CON PASIVO CORRIENTE (PC), MIENTRAS QUE EL ACTIVO NO CORRIENTE
     (ANC) SE FINANCIA CON PASIVO NO CORRIENTE (PNC) Y PATRIMONIO NETO (PN)
   - EVITAR AMPLIACIONES O REDUCCIONES DE CUENTAS DEL BALANCE QUE SE
     CONTRAPONGAN A LA COYUNTURA:
     - TOMAR O AUMENTAR LAS DEUDAS Y/O STOCK EN MOMENTOS DE RECESIÓN
     - OTORGAMIENTO DE CRÉDITOS SI SE PREVE QUIEBRAS O INCOBRABLES
     - VENTA DE MONEDA EXTRANJERA EN PROCESOS DE  DEVALUACION
   - EL ANALISIS DE ORIGEN Y APLICACIÓN DE FONDOS SE PUEDE COMBINAR CON EL
     ANALISIS DE OTRAS HERRAMIENTAS (BASADOS EN OTROS DOCUMENTOS
     CONTABLES). EJEMPLO RATIOS DE DIAS: DIAS DE CAJA, DIAS DE STOCK, DIAS DE
     PROVEEDORES, DIAS DE CREDITOS, ETC (LIBRO MAYOR).

* TODO Capital de Trabajo
  - EL CAPITAL DE TRABAJO (KT) ES LA PARTE DEL ACTIVO CORRIENTE QUE NO ESTA
    FINANCIADA POR EL PASIVO CORRIENTE (DEUDA DE TERCEROS A CORTO PLAZO):
#+begin_example
    KT = Activo Corriente - Pasivo Corriente (enfoque en Activo Circulante)

    KT = Pasivo No Corriente + Patrimonio Neto - Activo No Corriente (enfoque en Capital Permanente)
#+end_example

  - ES LA PARTE DEL ACTIVO CORRIENTE FINANCIADA CON RECURSOS DE CARÁCTER
    NO CORRIENTE (“PERMANENTE”).

  *El Capital de Trabajo también llamado “Fondo de Maniobra”, debe ser
  considerado como parte de la inversión necesaria para un proyecto.

  - CONVIENE QUE EL KT SEA LO MAS CHICO POSIBLE. SE BUSCA QUE SEA POSITIVO,
    TENDIENDO A CERO.
    - KT NEGATIVO IMPLICA QUE EL PASIVO CORRIENTE (EXIGIBLE) ES MAYOR QUE EL
      ACTIVO CORRIENTE (LIQUIDO O CONVERTIBLE EN LIQUIDO DENTRO DEL EJERCICIO
      CONTABLE). ESTO LLEVA A PROBLEMAS DE BACHE FINANCIERO.
    - KT POSITIVO MUY CERCANO A CERO PUEDE SER RIESGOSO, DEBIDO A QUE PROBLEMAS
      EN LAS VENTAS (DESCENSO), CREDITOS (INCOBRABLES), ETC. PUEDEN PRODUCIR
      TAMBIEN SITUACIONES DE BACHE FINANCIERO.
    - KT POSITIVO Y MUY GRANDE SUELE ESTAR ASOCIADO A EXCEDENTES FINANCIEROS (NO
      OPTIMIZADOS).
 
 
 
 
 

