
* Introduccion

Capital: cualquier suma de dinero capaz de ser invertida. cualquier bien
susceptible de ser medido en terminos monetarios, por ej: terrenos, edificios,
instalaciones, etc.

Tasa de Interes: rendimiento de un Capital en la unidad de tiempo.

Interes: la masa de dinero generada por un Capital colocado, durante un cierto
tiempo, a una determinada tasa de interes.

Capitalizacion: accion de sumar a un capital, los intereses producidos por el
mismo.

Monto: suma de Capital mas el interes devengado por el mismo.

* Conceptos basicos
** Interes simple

un capital C es colocado a interes simple, cuando el interes es proporcional al
mismo y el tiempo t durante el cual ha sido colocado.

el coeficiente de proporcionalidad es la tasa de interes simple:

$$I = i * C * t$$

donde:

C: Capital
I: Interes
i: Tasa de interes [medido en 1/Unidad de tiempo]
t: Tiempo [medido en Unidad de tiempo]

para que la ecuacion sea valida, la tasa de interes y el periodo durante el cual
se realiza la operacion deben estar expresados en la misma unidad de tiempo.

** Tasa proporcional
en caso de que la tasa de interes y el periodo de la operacion no esten en la
misma unidad de tiempo, se introduce la tasa proporcional i_{p}.  La tasa
proporcional es la tasa anual divido el periodo en la cual se quiere obtener la
tasa proporcional, (semestral, trimestral, mensual, diaria)

Ej: cual es el interes generado por un C = 100 colocado durante 15 meses a una
tasa de 18% anual?

calculamos la tasa proporcional mensual $i_{p}$

i_{p} = 18% anual / (12 meses/año) = 1.5% mensual

I = i * C * t = 1.5% * $100 * 15 meses = $22.5

** Monto a interes simple
un capital C, colocado durante un tiempo T , y a una tasa de interes i, genera
al cabo de dico tiempo un monto M.

$$M = C * I$$

$$M = C * (1 + i*t)$$

el monto se denomina "a interes simple", puesto que los intereses adicionados,
son exclusivamente producidos por el Capital original.

** Interes compuesto, Monto a Interes compuesto

un capital ha sido colocado a interes compuesto, cuando se conviene que el
interes producido por el, al final de cada itnervalo de tiempo previamente
determinado, llamado periodo de capitalizacion, se suma dicho capital para
devengar interes en el periodo siguiente, en las mismas condiciones que el
capital inicial.

El monto al cabo de la enesima capitalizacion sera de

$$M_{n} = C (1+i)^{n}$$

(la tasa i y la cantidad de periodos n estan refiriendose a la misma unidad de
tiempo)

La expresion $(1+i)^{n}$ recibe el nombre de *Factorizacion de Capitalizacion*



Supongamos que un capital se deposita durante un periodo t (años), capitalizando
intereses m veces por año, a una tasa nominal anual i_{N},

$$i_{p} = \frac{i_{N}}{m}$$

n = cantidad de periodos de capitalizacion = m * t

M = C (1 + \frac{i_{N}}{m})^{m*t}


El valor del interes compuesto $I_{N}$ al cabo de n periodos de capitalizacion
es:

$$I_{N} = C ((1+i)^{n}-1)$$

$$I = C ((1+\frac{i_{N}}{m})^{m*t}-1)$$

La ecuacion sera valida incluso si n = m * t no es un numero entero.

** Interes Compuesto. Valor actual

Que capital C debo colocar para obtener al cabo de un tiempo t un monto m?

$$C = \frac{M}{(1+i)^{n}}$$

Surge aqui el concepto de actualizacion.

C es el valor actual de un Monto M obtenido en n periodos posteriores, y
representa el precio que debe pagarse por un capital para su posesion antes de
su vencimiento.

La expresion $\frac{1}{(1+i)^{n}}$ recibe el nombre de *Factor de
Actualizacion*.

** Tasa nominal

Cuando se fija una tasa anual, y se capitaliza en periodos mas cortos que el
año, la tasa anual recibe el nombre de nominal.

** Tasa efectiva

siendo

$C$: capital
$i_{p} = \frac{i_{N}}{m}$ : tasa proporcional
$m$: cantidad de periodos de capitalizacion por año
$i_{N}$: tasa nominal anual

si se capitalizan los intereses al fin de cada periodo a la misma tasa, al cabo
del año tendremos, por interes compuesto, un monto

$$M = C (1+i_{p})^{m} = C(1+\frac{i_{N}}{m})^{m}$$

se llama *tasa efectiva anual* $i_{ef}$ a la tasa de interes simple que,
aplicada al mismo capital, produce igual monto M en un año

$$M = C (1+i_{ef})^{1}$$

donde

$$i_{ef} = TEA = (1+\frac{i_{N}}{m})^{m}-1$$

$$TEA (%) = [(1+\frac{i_{N} (%) * dias}{36500}) ^ { \frac{365}{dias}} - 1] *
100$$

donde *dias* = cantidad de dias a los cuales se efectua el deposito

ambas ecuaciones son similares ya que , los periodos de capitalizacion por año m
es 365 / *dias*

$m = \frac{365}{dias}$

** Tasa equivalente

las tasas equivalentes, con periodos de capitalizacion diferentes, y aplicadas a
capitales iguales, producen montos iguales al cabo del mismo tiempo, es decir
que tienen la misma tasa efectiva.

$$i_{1} = (1+i_{2})^{\frac{n_{2}}{n_{1}}} - 1$$

** Capitalizacion Continua

(segun lo que entiendo de wikipedia, se usa para calcular el monto final
capitalizando los intereses. La tasa de interes se mantiene constante .

El monto con capitalizacion continua es:

$$M = C * e^{i_{N} * t}$$

donde i_{N}:TNA y t:numero de años)

** Tasa instantanea

$\delta$ : la tasa que aplicada a un capital con regimen de capitalizacion
continua, produce al cabo de un tiempo un monto a interes compuesto igual al
obtenido mediante el empleo de la formula fundamental del monto, en el mismo
intervalo de tiempo, y cuya tasa efectiva sea $i_{ef}$.

$C*e^{\delta * t} = C(1+i)^{m*t}$ para $t=1$

$C*e^{\delta} = C(1+i)^{m} = C(1+i_{ef})$

$e^{\delta} = 1 + i_{ef}$

** Descuento

un documento de credito tiene dos valores: el valor escrito en el mismo, llamado
valor nominal $N$, que es la cantidad que debe pagarse al dia de su vencimiento,
y el valor que tiene en cualquier monento si se lo descuenta, ie si se lo paga
antes de su vencimiento. Este valor recibe el nombre de valor actual.

el acreedor puede solicitar el pago anticipadamente.

** Descuento Simple / Descuento Comercial

Sean:

$N$: valor nominal del documento
$t$: tiempo que resta para su vencimiento
$d$: tasa de descuento

El Valor Actual del documento es:

$$A = N - N * d * t = N (1-d*t)$$

El descuento aplicado es

$$D = N * d * t$$

(La tasa de descuento y el tiempo deben estar referidos a las misma unidad)

Son aplicables los mismos conceptos de tasas nominales y proporcionales vistos
anteriormente.

se aplica en general en transacciones a corto plazo, pues de lo contrario se
puede llegar al caso de aplicar un descuento D tan grande como el valor nominal
N del documento. Para operaciones a largo plazo se utiliza el descuento
compuesto.

** Equivalencia entre tasa vencida o de interes i y tasa adelantada o de descuento d

$$d = \frac{i}{1+i*t}$$

o

$$i = \frac{d}{1-d*t}$$

una modalidad llamada *descuento matematico o racional* consiste en aplicar al
valor nominal la tasa vencida i en lugar de la tasa adelantada d:

$$A = \frac{N}{1+i*t}$$

** Descuento Compuesto

Sea

N: el valor nominal de un documento que vence al cabo de un tiempo t
d: la tasa de descuento compuesto a aplicar
n: la cantidad de periodos de actualizacion incluidos en el tiempo t

al fin del periodo n, el valor actual coincide con el valor nominal N; al cabo
del periodo n-1 es:

$$A_{n-1} = N - D = N - d*N = N (1-d)$$

al cabo del periodo n-2 es :

$$A_{n-2} = A_{n-1}-D = N(1-d)^{2}$$

Al cabo del periodo 0, el valor actual del documento es

$$A = N (1-d)^{n}$$

En esta expresion, la tasa d y la cantidad de periodos n deben estan referidos a
la misma unidad de tiempo.

Para ello, debemos aplicar nuevamente el concepto de tasa proporcional.

Supongamos que :

$d_{N}$ : tasa nominal de descuento
$m$: periodos de actualizacion por año.
n = m*t

luego

$$A = N (1-\frac{d_{N}}{m})^{m*t}$$

El *descuento compuesto D_{n} es:

$$D_{n} = N - A = N - N (1 - d)^{n} = N (1-(1-d)^{n})$$

o bien

$$D_{n} = N (1-(1-\frac{d_{N}}{m})^{m*t})$$

** Equivalencia entre tasa de descuento o adelantada d vs tasa de interes vencida i en el descuento compuesto

d: tasa de descuento o tasa adelantada
i: tasa de interes vencida

$$d = 1-\frac{1}{1+i} = \frac{i}{1+i}$$

$$i = \frac{d}{1-d}$$

tambien es aplicable el descuento matematico compuesto. aplicando el valor
nominal la tasa vencida i resulta:

$$A = \frac{N}{(1+i)^{n}}$$

** Tasa de interes real

a menudo, en operaciones comunes, nos encontramos que debemos evaluar si nos
conviene o no colocar dinera a interes, debiendo adoptar nuestra decision en
base a la expectativa de inflacion que tenemos.

la denominada tasa de interes real esta referida a operaciones en las cuales
deben tenerse en cuenta el efecto inflacionario. las diferentes tasas de interes
vistas en el presente trabajo no tienen en cuenta la existencia de inflacion, y
por eso es que suelen denominarse genericamente tasas nominales de interes.

sea C_{0} el capital disponible en el instante t_{0}

lo podemos invertir a un año a la tasa efectiva i_{ef}, obteniendo al cabo de
dicho año un nuevo Capital C_{1} = C_{0} (1+i_{ef})

Ahora bien, en el instante t_{0} podemos comprar una cantidad q_{0} de
determinada canasta de productos a precio promedio p_{0}; Q_{0} =
\frac{C_{0}}{P_{0}}

transcurrido un año , el precio de productos habra aumentado a $P_{1}: P_{1} =
P_{0} (1+f)$, donde f es *tasa de inflacion anual*.

luego la cantidad que podremos adquirir al cabo de un año sera

$$Q_{1} = \frac{C_{1}}{P_{1}}$$

$Q_{1}$: cantidad que se puede adquirir al cabo de un año
$C_{1}$: capital disponible en el instante t_{1}
$P_{1}$: precio de los productos en el instante t_{1}

se define como *interes real* a:

$$i_{R} = \frac{1+i_{ef}}{1+f}-1$$


* Rentas
** def

serie de pagos iguales y realizados a intervalos constantes.

R: cuota , anualidad o termino de la renta

las cuotas o anualidades pueden recibir el nombre de
- *imposiciones* cuando se trata de una serie de cantidades que se abonan con el
  objeto de formar un capital
- *amortizaciones* cuando el objeto de las cuotas es la extincion de una deuda.

las cuotas o terminos de la renta pueden recibir el nombre generico de
*anualidades* aun cuando el periodo que media entre dos cuotas sea distinto a un
año.

** Valor actual de una renta de pagos vencidos

sea i la tasa de interes equivalente para el periodo comprendido entre dos
pagos, a la que se desea calcular dicho valor actual.

entonces, el valor actual de la primer cuota sera $\frac{R}{(1+i)}$
el valor actual de la enesima cuota sera $\frac{R}{(1+i)^{n}}$

el valor actual de la renta de pagos vencidos (P) es la suma de los valores
actuales de cada una de las cuotas:

$$P = \frac{R}{1+i} + \frac{R}{(1+i)^2} + ... + \frac{R}{(1+i)^n}$$

$$P = VA = R (\frac{(1+i)^{n} -1}{(1+i)^{n} i})$$

se define el coeficiente *Factor de Amortizacion*:

$$a_{n|_{i}} = \frac{(1+i)^n - 1}{i(1+i)^n}$$

como el valor actual de una renta constituida por n cuotas de $1 a la tasa i.

resulta entonces $$P = R * a_{\frac{n}{i}}$$

** Valor actual de una renta de pagos anticipados

El valor actual de la renta de pago anticipados, al que llamamos P' resultara:

$$P' =  R + \frac{R}{(1+i)}  + \frac{R}{(1+i)^2} + ... + \frac{R}{(1+i)^{n-1}}$$

$$P' (1+i)^{n-1} = R [1+(1+i)+...+(1+i)^{n-1}]$$

la expresion entre corchetes es la suma de una progresion geometrica de razon $q
= (1+i)$ de manera que resulta:

$$P' = R \frac{(1+i)^{n}-1}{i(1+i)^{n-1}}$$

$$P' = P (1+i)$$

** Monto de una renta de pagos vencidos

S: sumatoria del Valor Futuro de todas las rentas desde R en el periodo 1.
Monto de una renta de n cuotas de $1 a la tasa i

$$S = P (1+i)^{n}$$

$$ S = R\frac{(1+i)^{n}-1}{i}$$


*Factor de imposicion*: $s_{n|_{i}} = \frac{(1+i)^{n}-1}{i}$

** Monto de una renta de pagos anticipados

S' = R [\frac{(1+i)-1}{i}](1+i) = S (1+i)

** Equivalencia de series de pago

dada una tasa i, se dice que dos series de pago son equivalentes cuando sus
valores actuales a dichas tasa son coincidentes.

** tabla de factores

| Factor de      |                              |                                     |
| capitalizacion | (1+i)^n                      | S = P(1+i)^n                        |
| actualizacion  | \frac{1}{(1+i)^n}            | P = \frac{S}{(1+i)^n}               |
| amortizacion   | \frac{(1+i)^n - 1}{i(1+i)^n} | P = R[\frac{(1+i)^n - 1}{i(1+i)^n}] |
| imposicion     | \frac{(1+i)^n -1 }{i}        | S = R[\frac{(1+i)^n -1 }{i}]        |

| Renta de pagos vencidos | R = P[\frac{i(1+i)^n}{(1+i)^n - 1}] |P=VA;R cuota
| Renta de montos futuros | R = S[\frac{i}{(1+i)^n -1 } ]       |S=VF;R cuota


* Amortizacion de prestamos

amortizar una deuda es el proceso por el cual se la extingue ya sea mediante un
pago unico o con una sucesion de pagos en el tiempo.

Para establecer el macenismo de amortizacion se debera fijar:

- el interes a aplicar en la operacion
- forma de calculo y oportunidad de pago de los intereses
- forma de devolucion del capital

** Sistema frances

Cuota constante mayor que los intereses producidos por la suma adeudada en un
periodo, el \delta = cuota - intereses devengados \rightarrow para amortizar el
prestamo. Tambien llamado sistema de amortizacion progresiva.

P = monto del prestamo,
i = tasa de interes
n = numero de cuotas
R = cuota, cte

R = I_{j} + A_{j}

I_{j} interes de la deuda

A_{j} comp de amortizacion cuota

$$R = P \frac{i(1+i)^n}{(1+i)^n -1}$$

$A_{j} = A_{1} (1+i)^{j-1}$

 **** calculo de la cuota,
sea P el monto del prestamo
n el numero de cuotas
i la tasa de interes
R la cuota

y supongamos que la primer cuota me abona un periodo despues de entregado el prestamo.

graficamente:

GRAFICO


si quisieramos calcular R nos bastaria utilizar la expresion encotrada en el capitulo de renta, resultando:

R = P \frac{1(1+i)^{n}}{(1+i)^{n}-1}

 **** componentes de la cuota : amortizacion e interes

hemos dicho que la cuota R incluye tanto el pago de intereses como la amortizacion del capital, por lo que podriamos escrbir

R = cte = I_{j} + A_{j}

donde I_{j}: componente de interes de la cuota j
A_{j}: componente de interes de amortizacion de la cuota j


veamos como varia A_{j}, ya que hemos dicho que la cuota es constante, pero no lo son cada uno de sus componentes.

al tener que abonar la primer cuota , dado que nada del capital ha sido devuelto, el interes incluido en dicha cuota debera calcularse sobre el prestamos original , por lo que:

I_{1} = P_{1}

y como R = I_{1} + A_{1} y A_{1} = R ñ P_{1}

al abonar la primer cuota , en consecuencia, la parte del capital  que queda por amortizar sera:

P-A_{1} = P-R+P_{1}

** Sistema aleman

de acuerdo a este sistema el prestamo se devuelve en n amortizaciones constantes
(e iguales c/u a la enesima parte del prestamo) y paga al comienzo o al cabo de
cada periodo los intereses devengados.  por el capital que se adeuda.

si $P$ es el prestamo , las amortizaciones son iguales a $\frac{P}{n}$ y por lo
tanto, el interes disminuye en $\frac{P}{n} i$ por periodo.

llamaremos $R$ al valor de las cuotas y supondremos inicialmente que los
intereses se pagan por periodo vencido.

$$R_{m} = \frac{P}{n} + (P-\frac{P(m-1)}{n})i$$

si los intereses se pagaran por adelantado seria:

$R_{0} = P*i$ (no hay en este primer pago amortizacion de capital)

$R_{m} = \frac{P}{n} + (P-\frac{P*m}{n})i$ para m \neq 0

** Sistema americano

1. al final de cada periodo se paga solo el interes simple de la deuda total
   devengada en ese periodo
2. se depositan al fin de cada periodo sumas constantes tales que al
   capitalizarlos a interes compuesto formen al final de la operacion un capital
   igual a la deuda
3. al final del ultimo periodo se paga la totalidad de la deuda con el capital
   acumulado en 2.

$$R = P*i+t$$
$$P = t\frac{(1+i')^{n}-1}{i'}$$

$$R = t = \frac{P*i'}{(1+i')^{n}-1}$$

i: tasa estipulada para el prestamo
i': tasa con que capitaliza t

** interes directo

$$R = \frac{P}{n}+i*P
